import os

from setuptools import setup, find_packages

here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, "README.md")) as f:
    README = f.read()
with open(os.path.join(here, "CHANGES.txt")) as f:
    CHANGES = f.read()

requires = [
    "alabaster",
    "alembic",
    "amqp",
    "a2wsgi",
    "appdirs",
    "arrow",
    "attrs",
    "Babel",
    "backports.csv",
    "beautifulsoup4",
    "billiard",
    "binaryornot",
    "black",
    "boto",
    "celery",
    "certifi",
    "cffi",
    "chardet",
    "charset-normalizer",
    "click",
    "click-didyoumean",
    "click-plugins",
    "click-repl",
    "cookiecutter",
    "coverage",
    "cryptography",
    "decorator",
    "docutils",
    "elasticsearch",
    "emoji",
    "fastapi",
    "feedparser",
    "FormEncode",
    "future",
    "greenlet",
    "idna",
    "imagesize",
    "importlib-resources",
    "iniconfig",
    "itsdangerous",
    "jaraco.classes",
    "jaraco.collections",
    "jaraco.functools",
    "jaraco.text",
    "Jinja2",
    "jinja2-time",
    "joblib",
    "kombu",
    "linecache2",
    "lxml",
    "MarkupSafe",
    "more-itertools",
    "mypy-extensions",
    "mysql-connector-python",
    "mysqlclient",
    "nose",
    "numpy",
    "ofs",
    "packaging",
    "paginate",
    "paho-mqtt",
    "Pairtree",
    "pandas",
    "pathspec",
    "pdfminer.six",
    "Pillow",
    "platformdirs",
    "pluggy",
    "poyo",
    "prompt-toolkit",
    "protobuf",
    "py",
    "pycparser",
    "pycryptodome",
    "Pygments",
    "pyparsing",
    "pytest",
    "pytest-cov",
    "python-dateutil",
    "python-docx",
    "python-editor",
    "python-multipart",
    "python-slugify",
    "pytz",
    "PyUtilib",
    "pyxform",
    "qrcode",
    "redis",
    "regex",
    "requests",
    "scipy",
    "sgmllib3k",
    "simplekml",
    "six",
    "snowballstemmer",
    "sortedcontainers",
    "soupsieve",
    "Sphinx",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "SQLAlchemy",
    "starlette",
    "text-unidecode",
    "timeago",
    "toml",
    "tomli",
    "tqdm",
    "traceback2",
    "typing-extensions",
    "unicodecsv",
    "unittest2",
    "urllib3",
    "uvicorn",
    "validators",
    "vine",
    "wcwidth",
    "WebHelpers2",
    "WebOb",
    "WebTest",
    "xlrd",
    "zc.lockfile",
    "zipp",
]

postgresql_requires = ["psycopg2"]

sqlserver_requires = ["pyodbc"]

tests_require = ["WebTest >= 1.3.1", "pytest", "pytest-cov"]  # py3 compat

setup(
    name="formshare",
    version="3.0.0",
    description="FormShare",
    long_description=README + "\n\n" + CHANGES,
    classifiers=[
        "Programming Language :: Python",
        "Framework :: FastAPI",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: ASGI :: Application",
    ],
    author="",
    author_email="",
    url="",
    keywords="web fastapi",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    extras_require={"testing": tests_require},
    install_requires=requires,
    entry_points={
        "console_scripts": [
            "create_superuser = formshare.scripts.createsuperuser:main",
            "configure_mysql = formshare.scripts.configuremysql:main",
            "configure_alembic = formshare.scripts.configurealembic:main",
            "modify_config = formshare.scripts.modifyconfig:main",
            "configure_tests = formshare.scripts.configuretests:main",
            "update_aes_key = formshare.scripts.updateaeskey:main",
        ],
    },
)
