version: '3'
services:
  fsmysql_20201123:
    image: mysql:5.7.27
    container_name: fs_mysql_20201123
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password
    volumes:
      - /opt/formshare/mysql:/var/lib/mysql
    networks:
      fsnet:
        ipv4_address: 172.28.1.5
  
  fselasticsearch_20201123:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch_20201123
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=172.28.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.1
  fselasticsearch2_20201123:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch2_20201123
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=172.28.1.2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.28.1.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata2:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.2
  fselasticsearch3_20201123:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch3_20201123
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=172.28.1.3
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.28.1.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata3:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.3
  formshare_20201123:
    image: qlands/formshare2:20201123
    container_name: formshare_20201123
    environment:
      MYSQL_HOST_NAME: 172.28.1.5
      MYSQL_USER_NAME: root
      MYSQL_USER_PASSWORD: my_secure_password
      FORMSHARE_ADMIN_USER: admin
      FORMSHARE_ADMIN_EMAIL: admin@myserver.com
      FORMSHARE_ADMIN_PASSWORD: my_secure_password
      ELASTIC_SEARCH_HOST: 172.28.1.1
      ELASTIC_SEARCH_PORT: 9200
      FORMSHARE_HOST: 172.28.1.4
      FORMSHARE_PORT: 5900
      FORWARDED_ALLOW_IP: 172.28.1.4
      CONFIGURE_FLUENT: "false"
      WAIT_HOSTS: 172.28.1.5:3306, 172.28.1.1:9200
      WAIT_HOSTS_TIMEOUT: 120
    volumes:
      - /opt/formshare/repository:/opt/formshare_repository
      - /opt/formshare/log:/opt/formshare_log
      - /opt/formshare/celery:/opt/formshare_celery
      - /opt/formshare/config:/opt/formshare_config
      - /opt/formshare/fluentd:/opt/formshare_fluentd
      - /opt/formshare/plugins:/opt/formshare_plugins
      - fsokdtools:/opt/odktools
      - fssource:/opt/formshare
    ports:
      - 5900:5900
    networks:
      fsnet: 
        ipv4_address: 172.28.1.4

  fsapache_20201123:
    image: qlands/httpd:2.4
    container_name: fsapache_20201123
    ports:
      - 80:80
    networks:
      fsnet:
        ipv4_address: 172.28.1.6
      
networks:
  fsnet:
     ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16

volumes:
  fsokdtools:
    driver: local
  fssource:
    driver: local