"""Added table of project files

Revision ID: 019967069cf0
Revises: 87f2a566911d
Create Date: 2018-11-18 08:39:19.845537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019967069cf0'
down_revision = '87f2a566911d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectfile',
                    sa.Column('file_id', sa.Unicode(length=64), nullable=False),
                    sa.Column('project_id', sa.Unicode(length=64), nullable=False),
                    sa.Column('file_name', sa.Unicode(length=120), nullable=True),
                    sa.Column('file_udate', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_projectfile_project_id_project'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_projectfile')),
                    mysql_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectfile')
    # ### end Alembic commands ###
