"""Add assistant password to user

Revision ID: 03441e0d7d31
Revises: 84032d0b43d2
Create Date: 2025-08-15 13:53:42.307793

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "03441e0d7d31"
down_revision = "84032d0b43d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fsuser",
        sa.Column(
            "user_assistant_password",
            mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fsuser", "user_assistant_password")
    # ### end Alembic commands ###
