"""Control users to add project and forms

Revision ID: 04268f3259f2
Revises: 1f4badb4de3f
Create Date: 2023-07-20 11:09:05.351583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04268f3259f2"
down_revision = "1f4badb4de3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fsuser",
        sa.Column(
            "user_can_projects",
            sa.INTEGER(),
            server_default=sa.text("'1'"),
            nullable=True,
        ),
    )
    op.add_column(
        "fsuser",
        sa.Column(
            "user_can_forms", sa.INTEGER(), server_default=sa.text("'1'"), nullable=True
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "project_encrypted",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_encrypted")
    op.drop_column("fsuser", "user_can_forms")
    op.drop_column("fsuser", "user_can_projects")
    # ### end Alembic commands ###
