"""Connect again the table of submission

Revision ID: 0432d44dc77f
Revises: 777ad93c6382
Create Date: 2025-08-25 10:16:11.116968

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0432d44dc77f"
down_revision = "777ad93c6382"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_submission_enumerator1_idx", "submission", ["coll_uuid"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_submission_coll_uuid_collaborator"),
        "submission",
        "collaborator",
        ["coll_uuid"],
        ["coll_uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_submission_coll_uuid_collaborator"), "submission", type_="foreignkey"
    )
    op.drop_index("fk_submission_enumerator1_idx", table_name="submission")
    # ### end Alembic commands ###
