"""Fix json history

Revision ID: 0801e2a5042c
Revises: cf90ef87eb87
Create Date: 2025-08-30 04:58:35.505394

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0801e2a5042c"
down_revision = "cf90ef87eb87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jsonhistory",
        "enum_project",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
        nullable=True,
    )
    op.alter_column(
        "jsonhistory",
        "coll_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jsonhistory",
        "coll_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=False,
    )
    op.alter_column(
        "jsonhistory",
        "enum_project",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
        nullable=False,
    )
    # ### end Alembic commands ###
