"""Restrict delete of project or user

Revision ID: 0bc56c77ec06
Revises: b476703716fc
Create Date: 2025-09-18 09:27:15.582162

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0bc56c77ec06"
down_revision = "b476703716fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_odkform_project_id_project", "odkform", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_odkform_project_id_project"),
        "odkform",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        "fk_userproject_user_id_fsuser", "userproject", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_userproject_user_id_fsuser"),
        "userproject",
        "fsuser",
        ["user_id"],
        ["user_id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_userproject_user_id_fsuser"), "userproject", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_userproject_user_id_fsuser",
        "userproject",
        "fsuser",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_odkform_project_id_project"), "odkform", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_odkform_project_id_project",
        "odkform",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
