"""Process only products

Revision ID: 19649c355612
Revises: f41d23fed275
Create Date: 2019-03-03 10:26:39.100447

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "19649c355612"
down_revision = "f41d23fed275"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "process_only", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "process_only")
    # ### end Alembic commands ###
