"""Initial version

Revision ID: 197264106674
Revises: 
Create Date: 2018-07-22 13:11:38.247898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197264106674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboratorlog',
    sa.Column('log_entry', sa.String(length=64), nullable=False),
    sa.Column('log_datetime', sa.DateTime(), nullable=True),
    sa.Column('access_type', sa.INTEGER(), nullable=True),
    sa.Column('interface', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.INTEGER(), nullable=True),
    sa.Column('userid', sa.String(length=255), nullable=True),
    sa.Column('org', sa.String(length=32), nullable=True),
    sa.Column('project', sa.String(length=32), nullable=True),
    sa.Column('form', sa.String(length=120), nullable=True),
    sa.Column('collaborator', sa.String(length=32), nullable=True),
    sa.Column('logid', sa.String(length=64), nullable=True),
    sa.Column('commitid', sa.String(length=12), nullable=True),
    sa.Column('schemaid', sa.String(length=13), nullable=True),
    sa.Column('tableid', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('log_entry', name=op.f('pk_collaboratorlog'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_password', sa.String(length=120), nullable=True),
    sa.Column('user_about', sa.Text(), nullable=True),
    sa.Column('user_cdate', sa.DateTime(), nullable=True),
    sa.Column('user_llogin', sa.DateTime(), nullable=True),
    sa.Column('user_super', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('user_active', sa.INTEGER(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('user_apikey', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )
    op.create_table('userlog',
    sa.Column('log_entry', sa.String(length=64), nullable=False),
    sa.Column('log_datetime', sa.DateTime(), nullable=True),
    sa.Column('access_type', sa.INTEGER(), nullable=True),
    sa.Column('tableid', sa.String(length=45), nullable=True),
    sa.Column('action', sa.INTEGER(), nullable=True),
    sa.Column('userid', sa.String(length=255), nullable=True),
    sa.Column('org', sa.String(length=32), nullable=True),
    sa.Column('project', sa.String(length=32), nullable=True),
    sa.Column('form', sa.String(length=120), nullable=True),
    sa.Column('collaborator', sa.String(length=32), nullable=True),
    sa.Column('groupid', sa.String(length=12), nullable=True),
    sa.Column('septable', sa.String(length=120), nullable=True),
    sa.Column('sepsection', sa.String(length=12), nullable=True),
    sa.Column('sepitem', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('log_entry', name=op.f('pk_userlog'))
    )
    op.create_table('project',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_abstract', sa.Text(), nullable=True),
    sa.Column('project_cdate', sa.String(length=45), nullable=True),
    sa.Column('project_creator', sa.String(length=45), nullable=True),
    sa.Column('project_cremail', sa.String(length=45), nullable=True),
    sa.Column('project_contact', sa.String(length=120), nullable=True),
    sa.Column('project_coemail', sa.String(length=45), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_project_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project'))
    )
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_table('collaborator',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.Column('coll_name', sa.String(length=120), nullable=True),
    sa.Column('coll_password', sa.String(length=120), nullable=True),
    sa.Column('coll_active', sa.INTEGER(), nullable=True),
    sa.Column('coll_cdate', sa.DateTime(), nullable=True),
    sa.Column('coll_email', sa.Text(), nullable=True),
    sa.Column('coll_telephone', sa.String(length=120), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('samas_project', sa.String(length=64), nullable=True),
    sa.Column('sameas_coll', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_collaborator_project_id_project'), ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['samas_project', 'sameas_coll'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_collaborator_samas_project_collaborator'), ondelete='NO ACTION', onupdate="NO ACTION"),
    sa.PrimaryKeyConstraint('project_id', 'coll_id', name=op.f('pk_collaborator'))
    )
    op.create_index('fk_enumerator_enumerator1_idx', 'collaborator', ['samas_project', 'sameas_coll'], unique=False)
    op.create_table('collgroup',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('group_desc', sa.Text(), nullable=True),
    sa.Column('group_cdate', sa.DateTime(), nullable=True),
    sa.Column('group_active', sa.INTEGER(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_collgroup_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'group_id', name=op.f('pk_collgroup'))
    )
    op.create_table('form',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('form_name', sa.String(length=120), nullable=True),
    sa.Column('form_cdate', sa.DateTime(), nullable=True),
    sa.Column('form_directory', sa.String(length=120), nullable=True),
    sa.Column('form_schema', sa.String(length=13), nullable=True),
    sa.Column('form_accsub', sa.INTEGER(), nullable=True),
    sa.Column('form_testing', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('form_incversion', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('parent_project', sa.String(length=64), nullable=True),
    sa.Column('parent_form', sa.String(length=120), nullable=True),
    sa.Column('form_stage', sa.INTEGER(), nullable=True),
    sa.Column('form_pkey', sa.String(length=120), nullable=True),
    sa.Column('form_deflang', sa.String(length=120), nullable=True),
    sa.Column('form_yesno', sa.String(length=120), nullable=True),
    sa.Column('form_othlangs', sa.Text(), nullable=True),
    sa.Column('form_sepfile', sa.Text(), nullable=True),
    sa.Column('form_xlsfile', sa.Text(), nullable=True),
    sa.Column('form_xmlfile', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['parent_project', 'parent_form'], ['form.project_id', 'form.form_id'], name=op.f('fk_form_parent_project_form'),ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_form_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', name=op.f('pk_form'))
    )
    op.create_index('fk_form_form1_idx', 'form', ['parent_project', 'parent_form'], unique=False)
    op.create_table('collingroup',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('enum_project', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.Column('coll_privileges', sa.INTEGER(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enum_project', 'coll_id'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_collingroup_enum_project_collaborator'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'group_id'], ['collgroup.project_id', 'collgroup.group_id'], name=op.f('fk_collingroup_project_id_collgroup'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', 'group_id', 'enum_project', 'coll_id', name=op.f('pk_collingroup'))
    )
    op.create_index('fk_enumingroup_enumerator1', 'collingroup', ['enum_project', 'coll_id'], unique=False)
    op.create_index('fk_enumingroup_enumerator1_idx', 'collingroup', ['enum_project', 'coll_id'], unique=False)
    op.create_table('formaccess',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.Column('form_project', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('coll_privileges', sa.INTEGER(), nullable=True),
    sa.Column('access_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_project', 'form_id'], ['form.project_id', 'form.form_id'], name=op.f('fk_formaccess_form_project_form'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'coll_id'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_formaccess_project_id_collaborator'), ondelete='NO ACTION', onupdate="NO ACTION"),
    sa.PrimaryKeyConstraint('project_id', 'coll_id', 'form_project', 'form_id', name=op.f('pk_formaccess'))
    )
    op.create_index('fk_submitter_form1', 'formaccess', ['form_project', 'form_id'], unique=False)
    op.create_index('fk_submitter_form1_idx', 'formaccess', ['form_project', 'form_id'], unique=False)
    op.create_table('formgrpaccess',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('form_project', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('access_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_project', 'form_id'], ['form.project_id', 'form.form_id'], name=op.f('fk_formgrpaccess_form_project_form'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'group_id'], ['collgroup.project_id', 'collgroup.group_id'], name=op.f('fk_formgrpaccess_project_id_collgroup'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', 'group_id', 'form_project', 'form_id', name=op.f('pk_formgrpaccess'))
    )
    op.create_index('fk_grpsubmitter_form1', 'formgrpaccess', ['form_project', 'form_id'], unique=False)
    op.create_index('fk_grpsubmitter_form1_idx', 'formgrpaccess', ['form_project', 'form_id'], unique=False)
    op.create_table('jsonlog',
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('log_dtime', sa.DateTime(), nullable=True),
    sa.Column('json_file', sa.Text(), nullable=True),
    sa.Column('log_file', sa.Text(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('enum_project', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['enum_project', 'coll_id'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_jsonlog_enum_project_collaborator'),ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'form_id'], ['form.project_id', 'form.form_id'], name=op.f('fk_jsonlog_project_id_form'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('form_id', 'project_id', 'log_id', name=op.f('pk_jsonlog'))
    )
    op.create_index('fk_jsonlog_enumerator1_idx', 'jsonlog', ['enum_project', 'coll_id'], unique=False)
    op.create_index('fk_jsonlog_form1_idx', 'jsonlog', ['project_id', 'form_id'], unique=False)
    op.create_table('septable',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('table_desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'form_id'], ['form.project_id', 'form.form_id'], name=op.f('fk_septable_project_id_form'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', 'table_name', name=op.f('pk_septable'))
    )
    op.create_table('submission',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('submission_dtime', sa.DateTime(), nullable=True),
    sa.Column('submission_status', sa.INTEGER(), nullable=True),
    sa.Column('enum_project', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.Column('md5sum', sa.String(length=120), nullable=True),
    sa.Column('sameas', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['enum_project', 'coll_id'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_submission_enum_project_collaborator'),ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'form_id'], ['form.project_id', 'form.form_id'], name=op.f('fk_submission_project_id_form'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', 'submission_id', name=op.f('pk_submission'))
    )
    op.create_index('fk_submission_enumerator1_idx', 'submission', ['enum_project', 'coll_id'], unique=False)
    op.create_index('fk_submission_form1_idx', 'submission', ['project_id', 'form_id'], unique=False)
    op.create_table('jsonhistory',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('log_sequence', sa.String(length=12), nullable=False),
    sa.Column('log_dtime', sa.DateTime(), nullable=True),
    sa.Column('log_action', sa.INTEGER(), nullable=True),
    sa.Column('log_commit', sa.String(length=12), nullable=True),
    sa.Column('log_notes', sa.Text(), nullable=True),
    sa.Column('enum_project', sa.String(length=64), nullable=False),
    sa.Column('coll_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['enum_project', 'coll_id'], ['collaborator.project_id', 'collaborator.coll_id'], name=op.f('fk_jsonhistory_enum_project_collaborator'),ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id', 'project_id', 'log_id'], ['jsonlog.form_id', 'jsonlog.project_id', 'jsonlog.log_id'], name=op.f('fk_jsonhistory_form_id_jsonlog'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', 'log_id', 'log_sequence', name=op.f('pk_jsonhistory'))
    )
    op.create_index('fk_jsonhistory_enumerator1_idx', 'jsonhistory', ['enum_project', 'coll_id'], unique=False)
    op.create_index('fk_jsonhistory_jsonlog1_idx', 'jsonhistory', ['form_id', 'project_id', 'log_id'], unique=False)
    op.create_table('sepsection',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('section_id', sa.String(length=12), nullable=False),
    sa.Column('section_name', sa.String(length=120), nullable=True),
    sa.Column('section_desc', sa.Text(), nullable=True),
    sa.Column('section_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id', 'form_id', 'table_name'], ['septable.project_id', 'septable.form_id', 'septable.table_name'], name=op.f('fk_sepsection_project_id_septable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', 'table_name', 'section_id', name=op.f('pk_sepsection'))
    )
    op.create_table('sepitems',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('table_name', sa.String(length=120), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('item_desc', sa.Text(), nullable=True),
    sa.Column('item_xmlcode', sa.Text(), nullable=True),
    sa.Column('item_notdisplay', sa.INTEGER(), nullable=True),
    sa.Column('item_order', sa.INTEGER(), nullable=True),
    sa.Column('section_project', sa.String(length=64), nullable=False),
    sa.Column('section_form', sa.String(length=120), nullable=False),
    sa.Column('section_table', sa.String(length=120), nullable=False),
    sa.Column('section_id', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'form_id', 'table_name'], ['septable.project_id', 'septable.form_id', 'septable.table_name'], name=op.f('fk_sepitems_project_id_septable'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_project', 'section_form', 'section_table', 'section_id'], ['sepsection.project_id', 'sepsection.form_id', 'sepsection.table_name', 'sepsection.section_id'], name=op.f('fk_sepitems_section_project_sepsection'), ondelete='NO ACTION', onupdate='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', 'form_id', 'table_name', 'item_name', name=op.f('pk_sepitems'))
    )
    op.create_index('fk_sepitems_sepsection1_idx', 'sepitems', ['section_project', 'section_form', 'section_table', 'section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_sepitems_sepsection1_idx', table_name='sepitems')
    op.drop_table('sepitems')
    op.drop_table('sepsection')
    op.drop_index('fk_jsonhistory_jsonlog1_idx', table_name='jsonhistory')
    op.drop_index('fk_jsonhistory_enumerator1_idx', table_name='jsonhistory')
    op.drop_table('jsonhistory')
    op.drop_index('fk_submission_form1_idx', table_name='submission')
    op.drop_index('fk_submission_enumerator1_idx', table_name='submission')
    op.drop_table('submission')
    op.drop_table('septable')
    op.drop_index('fk_jsonlog_form1_idx', table_name='jsonlog')
    op.drop_index('fk_jsonlog_enumerator1_idx', table_name='jsonlog')
    op.drop_table('jsonlog')
    op.drop_index('fk_grpsubmitter_form1_idx', table_name='formgrpaccess')
    op.drop_index('fk_grpsubmitter_form1', table_name='formgrpaccess')
    op.drop_table('formgrpaccess')
    op.drop_index('fk_submitter_form1_idx', table_name='formaccess')
    op.drop_index('fk_submitter_form1', table_name='formaccess')
    op.drop_table('formaccess')
    op.drop_index('fk_enumingroup_enumerator1_idx', table_name='collingroup')
    op.drop_index('fk_enumingroup_enumerator1', table_name='collingroup')
    op.drop_table('collingroup')
    op.drop_index('fk_form_form1_idx', table_name='form')
    op.drop_table('form')
    op.drop_table('collgroup')
    op.drop_index('fk_enumerator_enumerator1_idx', table_name='collaborator')
    op.drop_table('collaborator')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('userlog')
    op.drop_table('user')
    op.drop_table('collaboratorlog')
    # ### end Alembic commands ###
