"""Link again collingroup

Revision ID: 1f6d575c0d2a
Revises: c481201868bb
Create Date: 2025-08-25 10:38:29.540774

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f6d575c0d2a"
down_revision = "c481201868bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_enumingroup_collaborator_idx", "collingroup", ["coll_uuid"], unique=False
    )
    op.create_index(
        "fk_enumingroup_group_idx",
        "collingroup",
        ["project_id", "group_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_collingroup_project_id_collgroup"),
        "collingroup",
        "collgroup",
        ["project_id", "group_id"],
        ["project_id", "group_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_collingroup_coll_uuid_collaborator"),
        "collingroup",
        "collaborator",
        ["coll_uuid"],
        ["coll_uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_collingroup_coll_uuid_collaborator"), "collingroup", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_collingroup_project_id_collgroup"), "collingroup", type_="foreignkey"
    )
    op.drop_index("fk_enumingroup_group_idx", table_name="collingroup")
    op.drop_index("fk_enumingroup_collaborator_idx", table_name="collingroup")
    # ### end Alembic commands ###
