"""Add case datetime variable

Revision ID: 1ffae93c82d2
Revises: 448376431f7b
Create Date: 2021-11-27 07:23:54.698672

"""
import sqlalchemy as sa
from alembic import op
from formshare.models.formshare import Odkform, DictField
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "1ffae93c82d2"
down_revision = "448376431f7b"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "odkform", sa.Column("form_casedatetime", sa.Unicode(length=120), nullable=True)
    )
    session = Session(bind=op.get_bind())
    forms = (
        session.query(Odkform.project_id, Odkform.form_id, Odkform.form_casedatetime)
        .filter(Odkform.form_case == 1)
        .filter(Odkform.form_casetype != 1)
        .all()
    )
    for a_form in forms:
        if a_form.form_casedatetime is None:
            fields = (
                session.query(DictField.field_name, DictField.field_type)
                .filter(DictField.project_id == a_form.project_id)
                .filter(DictField.form_id == a_form.form_id)
                .filter(DictField.table_name == "maintable")
                .all()
            )
            field_to_use = None
            for a_field in fields:
                if a_field.field_type == "datetime":
                    field_to_use = a_field.field_name
            if field_to_use is None:
                for a_field in fields:
                    if a_field.field_type == "date":
                        field_to_use = a_field.field_name
            if field_to_use is not None:
                session.query(Odkform).filter(
                    Odkform.project_id == a_form.project_id
                ).filter(Odkform.form_id == a_form.form_id).update(
                    {"form_casedatetime": field_to_use}
                )
            else:
                print(
                    "Warning. Followup Form ID {} in project {} does not have a date or datetime field".format(
                        a_form.form_id, a_form.project_id
                    )
                )

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_casedatetime")
    # ### end Alembic commands ###
