"""Remove unnecessary fields

Revision ID: 213734b12f44
Revises: 80c172946a90
Create Date: 2018-09-08 11:08:47.168451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '213734b12f44'
down_revision = '80c172946a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_coemail')
    op.drop_column('project', 'project_creator')
    op.drop_column('project', 'project_cremail')
    op.drop_column('project', 'project_contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_contact', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('project', sa.Column('project_cremail', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('project', sa.Column('project_creator', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('project', sa.Column('project_coemail', mysql.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
