"""New field for user email

Revision ID: 221d9f82a10d
Revises: 4f59ec12363e
Create Date: 2021-02-23 20:53:45.850561

"""
from pyramid.paster import get_appsettings, setup_logging
from alembic import context
from formshare.processes.elasticsearch.user_index import configure_user_index_manager
import requests

# revision identifiers, used by Alembic.
revision = "221d9f82a10d"
down_revision = "4f59ec12363e"
branch_labels = None
depends_on = None


def upgrade():

    new_mapping = {
        "properties": {
            "user_email": {"type": "text", "copy_to": ["all_data", "user_email2"]},
            "user_email2": {"type": "text", "analyzer": "email"},
        }
    }

    config_uri = context.config.get_main_option("formshare.ini.file", None)
    if config_uri is None:
        print(
            "This migration needs parameter 'formshare.ini.file' in the alembic ini file."
        )
        print(
            "The parameter 'formshare.ini.file' must point to the full path of the FormShare ini file"
        )
        exit(1)

    setup_logging(config_uri)
    settings = get_appsettings(config_uri, "formshare")
    user_index = configure_user_index_manager(settings)
    es_connection = user_index.create_connection()
    es_connection.indices.put_mapping(
        new_mapping, index=user_index.index_name, doc_type="user"
    )
    r = requests.post(
        "http://{}:{}/{}/_update_by_query?conflicts=proceed".format(
            user_index.host, user_index.port, user_index.index_name
        )
    )
    if r.status_code != 200:
        print("Cannot update with query")
        exit(1)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
