"""Change in date

Revision ID: 2348d90c7152
Revises: e6574044279f
Create Date: 2020-04-11 11:15:17.273799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2348d90c7152"
down_revision = "e6574044279f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taskmessages",
        "message_date",
        existing_type=mysql.TIMESTAMP(fsp=6),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taskmessages",
        "message_date",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(fsp=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
