"""Add last updated field to forms

Revision ID: 25bbfe2293d0
Revises: a38268564115
Create Date: 2019-02-17 10:19:13.273930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25bbfe2293d0"
down_revision = "a38268564115"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("odkform", sa.Column("form_lupdate", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_lupdate")
    # ### end Alembic commands ###
