"""Add column user active

Revision ID: 2a2723d2ee68
Revises: 7881cd04fabc
Create Date: 2017-11-30 14:19:11.341239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2723d2ee68'
down_revision = '7881cd04fabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_active', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_active')
    # ### end Alembic commands ###
