"""Change password to text

Revision ID: 2e67eb119c02
Revises: 7a782be521c1
Create Date: 2019-10-02 21:57:30.066310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e67eb119c02'
down_revision = '7a782be521c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collaborator', 'coll_password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fsuser', 'user_password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsuser', 'user_password',
               existing_type=sa.INTEGER(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('collaborator', 'coll_password',
               existing_type=sa.INTEGER(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
