"""Add repository task id

Revision ID: 303c3b7100f5
Revises: 6d7462bf45e5
Create Date: 2019-03-22 13:51:31.031108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303c3b7100f5'
down_revision = '6d7462bf45e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odkform', sa.Column('form_reptask', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odkform', 'form_reptask')
    # ### end Alembic commands ###
