"""Add tenent to project

Revision ID: 3173d062fdc9
Revises: dab4636d0433
Create Date: 2025-08-24 13:36:59.660068

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3173d062fdc9"
down_revision = "dab4636d0433"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("project_tenant", sa.Unicode(length=120), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_project_project_tenant_tenant"),
        "project",
        "tenant",
        ["project_tenant"],
        ["tenant_id"],
        ondelete="RESTRICT",
    )
    conn = op.get_bind()
    conn.execute("UPDATE project set project_tenant = 'main'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_tenant")
    # ### end Alembic commands ###
