"""Add publishable control for products

Revision ID: 387b1c2f9052
Revises: fc1b66b49bd4
Create Date: 2019-07-07 19:28:02.890884

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "387b1c2f9052"
down_revision = "fc1b66b49bd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "publishable", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "publishable")
    # ### end Alembic commands ###
