"""Disconnect jsonlog

Revision ID: 3f711d7877ca
Revises: 7a457467684a
Create Date: 2025-08-25 09:50:10.202641

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f711d7877ca"
down_revision = "7a457467684a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_jsonlog_enum_project_collaborator", "jsonlog", type_="foreignkey"
    )
    op.drop_index("fk_jsonlog_enumerator1_idx", table_name="jsonlog")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_jsonlog_enumerator1_idx",
        "jsonlog",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_jsonlog_enum_project_collaborator",
        "jsonlog",
        "collaborator",
        ["enum_project", "coll_id"],
        ["project_id", "coll_id"],
    )

    # ### end Alembic commands ###
