"""Add new fields to the assistant table

Revision ID: 40148cb4bf3a
Revises: 9ed435d735c4
Create Date: 2025-08-24 10:13:34.157697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40148cb4bf3a"
down_revision = "9ed435d735c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    op.add_column(
        "collaborator",
        sa.Column(
            "coll_type", sa.INTEGER(), server_default=sa.text("'1'"), nullable=True
        ),
    )
    op.add_column(
        "collaborator", sa.Column("coll_tenant", sa.Unicode(length=120), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_collaborator_coll_tenant_tenant"),
        "collaborator",
        "tenant",
        ["coll_tenant"],
        ["tenant_id"],
        ondelete="RESTRICT",
    )
    conn = op.get_bind()
    conn.execute("UPDATE collaborator set coll_uuid = uuid()")
    conn.execute("UPDATE collaborator set coll_tenant = 'main'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_collaborator_coll_tenant_tenant"), "collaborator", type_="foreignkey"
    )
    op.drop_column("collaborator", "coll_tenant")
    op.drop_column("collaborator", "coll_type")
    op.drop_column("collaborator", "coll_uuid")
    # ### end Alembic commands ###
