"""Add form target

Revision ID: 415a14a81315
Revises: 759ef01e4971
Create Date: 2018-11-20 11:18:58.406789

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "415a14a81315"
down_revision = "759ef01e4971"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("odkform", sa.Column("form_target", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_target")
    # ### end Alembic commands ###
