"""Remove separate item table

Revision ID: 439e75118151
Revises: cacae7cd1a74
Create Date: 2019-08-31 23:38:33.570494

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "439e75118151"
down_revision = "cacae7cd1a74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sepitems")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sepitems",
        sa.Column("project_id", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("form_id", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("table_name", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("item_name", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("item_desc", mysql.TEXT(), nullable=True),
        sa.Column("item_xmlcode", mysql.TEXT(), nullable=True),
        sa.Column(
            "item_notdisplay",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "item_order",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("section_project", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("section_form", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("section_table", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("section_id", mysql.VARCHAR(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id", "table_name"],
            ["septable.project_id", "septable.form_id", "septable.table_name"],
            name="fk_sepitems_project_id_septable",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_project", "section_form", "section_table", "section_id"],
            [
                "sepsection.project_id",
                "sepsection.form_id",
                "sepsection.table_name",
                "sepsection.section_id",
            ],
            name="fk_sepitems_section_project_sepsection",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "form_id", "table_name", "item_name"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_sepitems_sepsection1_idx",
        "sepitems",
        ["section_project", "section_form", "section_table", "section_id"],
        unique=False,
    )
    # ### end Alembic commands ###
