"""New field to control language merge errors

Revision ID: 448376431f7b
Revises: b70e2621058e
Create Date: 2021-09-23 09:05:25.770747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "448376431f7b"
down_revision = "b70e2621058e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "odkform",
        sa.Column(
            "form_mergelngerror",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_mergelngerror")
    # ### end Alembic commands ###
