"""Connect again the table of jsonlog

Revision ID: 4d97d0eedaf3
Revises: 0432d44dc77f
Create Date: 2025-08-25 10:18:41.591281

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d97d0eedaf3"
down_revision = "0432d44dc77f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_jsonlog_enumerator1_idx", "jsonlog", ["coll_uuid"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_jsonlog_coll_uuid_collaborator"),
        "jsonlog",
        "collaborator",
        ["coll_uuid"],
        ["coll_uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_jsonlog_coll_uuid_collaborator"), "jsonlog", type_="foreignkey"
    )
    op.drop_index("fk_jsonlog_enumerator1_idx", table_name="jsonlog")
    # ### end Alembic commands ###
