"""Analyze user email

Revision ID: 4f59ec12363e
Revises: 77d7e4daa88d
Create Date: 2021-02-23 19:21:21.364171

"""
import requests
from pyramid.paster import get_appsettings, setup_logging
from alembic import context
from formshare.processes.elasticsearch.user_index import configure_user_index_manager
import time

# revision identifiers, used by Alembic.
revision = "4f59ec12363e"
down_revision = "77d7e4daa88d"
branch_labels = None
depends_on = None


def upgrade():

    email_analyzer = {
        "settings": {
            "analysis": {
                "filter": {
                    "email": {
                        "type": "pattern_capture",
                        "preserve_original": True,
                        "patterns": ["([^@]+)", "(\\p{L}+)", "(\\d+)", "@(.+)"],
                    }
                },
                "analyzer": {
                    "email": {
                        "tokenizer": "uax_url_email",
                        "filter": ["email", "lowercase", "unique"],
                    }
                },
            }
        }
    }

    config_uri = context.config.get_main_option("formshare.ini.file", None)
    if config_uri is None:
        print(
            "This migration needs parameter 'formshare.ini.file' in the alembic ini file."
        )
        print(
            "The parameter 'formshare.ini.file' must point to the full path of the FormShare ini file"
        )
        exit(1)

    setup_logging(config_uri)
    settings = get_appsettings(config_uri, "formshare")
    user_index = configure_user_index_manager(settings)
    es_connection = user_index.create_connection()
    use_ssl = settings.get("elasticsearch.user.use_ssl", "False")

    ready = False
    print("Waiting for ES to be ready")
    while not ready:
        if use_ssl == "False":
            resp = requests.get(
                "http://{}:{}/_cluster/health".format(user_index.host, user_index.port)
            )
        else:
            resp = requests.get(
                "https://{}:{}/_cluster/health".format(user_index.host, user_index.port)
            )
        data = resp.json()
        if data["status"] == "green":
            ready = True
        else:
            time.sleep(30)
    print("ES is ready")
    if use_ssl == "False":
        r = requests.post(
            "http://{}:{}/{}/_close".format(
                user_index.host, user_index.port, user_index.index_name
            )
        )
    else:
        r = requests.post(
            "https://{}:{}/{}/_close".format(
                user_index.host, user_index.port, user_index.index_name
            )
        )
    if r.status_code != 200:
        print("Cannot close")
        exit(1)
    es_connection.indices.put_settings(
        email_analyzer, index=settings["elasticsearch.user.index_name"]
    )
    if use_ssl == "False":
        r = requests.post(
            "http://{}:{}/{}/_open".format(
                user_index.host, user_index.port, user_index.index_name
            )
        )
    else:
        r = requests.post(
            "https://{}:{}/{}/_open".format(
                user_index.host, user_index.port, user_index.index_name
            )
        )
    if r.status_code != 200:
        print("Cannot open")
        exit(1)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
