"""Add original MD5

Revision ID: 4fd6a929c8b9
Revises: 135c7989d4b0
Create Date: 2020-12-20 18:09:41.401512

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4fd6a929c8b9"
down_revision = "135c7989d4b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column("original_md5sum", sa.Unicode(length=120), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "original_md5sum")
    # ### end Alembic commands ###
