"""Disable SSL in INI file

Revision ID: 5750ade545b3
Revises: b0d6a2d89fc7
Create Date: 2021-01-13 13:30:32.518183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5750ade545b3'
down_revision = 'b0d6a2d89fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
