"""Remove unused columns

Revision ID: 58d91afe341f
Revises: 0801e2a5042c
Create Date: 2025-09-01 14:29:36.569419

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "58d91afe341f"
down_revision = "0801e2a5042c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("formaccess", "project_id")
    op.drop_column("formaccess", "coll_id")
    op.drop_column("jsonhistory", "coll_id")
    op.drop_column("jsonhistory", "enum_project")
    op.drop_column("jsonlog", "coll_id")
    op.drop_column("jsonlog", "enum_project")
    op.drop_column("submission", "coll_id")
    op.drop_column("submission", "enum_project")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column(
            "enum_project",
            mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
    )
    op.add_column(
        "submission",
        sa.Column(
            "coll_id",
            mysql.VARCHAR(
                charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "jsonlog",
        sa.Column(
            "enum_project",
            mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
    )
    op.add_column(
        "jsonlog",
        sa.Column(
            "coll_id",
            mysql.VARCHAR(
                charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "jsonhistory",
        sa.Column(
            "enum_project",
            mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
    )
    op.add_column(
        "jsonhistory",
        sa.Column(
            "coll_id",
            mysql.VARCHAR(
                charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "formaccess",
        sa.Column(
            "coll_id",
            mysql.VARCHAR(
                charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "formaccess",
        sa.Column(
            "project_id",
            mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
