"""Add partner time bound access fields

Revision ID: 5e28705dda28
Revises: 22cde76e593c
Create Date: 2021-08-16 07:15:19.654766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5e28705dda28"
down_revision = "22cde76e593c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partnerform",
        sa.Column(
            "time_bound", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    op.add_column("partnerform", sa.Column("access_from", sa.DateTime(), nullable=True))
    op.add_column("partnerform", sa.Column("access_to", sa.DateTime(), nullable=True))
    op.add_column(
        "partnerform",
        sa.Column(
            "extras", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
    )
    op.add_column(
        "partnerform",
        sa.Column(
            "tags", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
    )
    op.add_column(
        "partnerproject",
        sa.Column(
            "time_bound", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    op.add_column(
        "partnerproject", sa.Column("access_from", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "partnerproject", sa.Column("access_to", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "partnerproject",
        sa.Column(
            "extras", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
    )
    op.add_column(
        "partnerproject",
        sa.Column(
            "tags", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partnerproject", "tags")
    op.drop_column("partnerproject", "extras")
    op.drop_column("partnerproject", "access_to")
    op.drop_column("partnerproject", "access_from")
    op.drop_column("partnerproject", "time_bound")
    op.drop_column("partnerform", "tags")
    op.drop_column("partnerform", "extras")
    op.drop_column("partnerform", "access_to")
    op.drop_column("partnerform", "access_from")
    op.drop_column("partnerform", "time_bound")
    # ### end Alembic commands ###
