"""Create new key for formaccess

Revision ID: 5f627adcc4a5
Revises: fa70adf2eb40
Create Date: 2025-08-25 10:26:43.420118

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5f627adcc4a5"
down_revision = "fa70adf2eb40"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column(
        "formaccess",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=True,
    )
    op.alter_column(
        "formaccess",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.alter_column(
        "formaccess",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.create_primary_key(
        op.f("pk_formaccess"),
        "formaccess",
        ["coll_uuid", "form_project", "form_id"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "formaccess",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.alter_column(
        "formaccess",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.alter_column(
        "formaccess",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=False,
    )
    op.execute("ALTER TABLE collaborator DROP PRIMARY KEY")
    # ### end Alembic commands ###
