"""Add API Key

Revision ID: 6088fadfc4d9
Revises: 2a2723d2ee68
Create Date: 2017-11-30 14:23:29.256319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6088fadfc4d9'
down_revision = '2a2723d2ee68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_apikey', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_apikey')
    # ### end Alembic commands ###
