"""Make tenant required

Revision ID: 694bf0fb0f92
Revises: 3173d062fdc9
Create Date: 2025-08-24 13:42:02.989540

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "694bf0fb0f92"
down_revision = "3173d062fdc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "project_tenant",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "project_tenant",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=True,
    )
    # ### end Alembic commands ###
