"""Add secondary session settings to ini

Revision ID: 6b09c0218d0b
Revises: b0d6a2d89fc7
Create Date: 2021-01-16 07:54:33.688670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b09c0218d0b'
down_revision = 'b0d6a2d89fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
