"""New linking to user

Revision ID: 6c4832148100
Revises: eab2cc23d659
Create Date: 2025-08-05 21:24:53.891715

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6c4832148100"
down_revision = "eab2cc23d659"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fsuser", sa.Column("user_tenant", sa.Unicode(length=120), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_fsuser_user_tenant_tenant"),
        "fsuser",
        "tenant",
        ["user_tenant"],
        ["tenant_id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "tenant",
        sa.Column(
            "tenat_active", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant", "tenat_active")
    op.drop_constraint(
        op.f("fk_fsuser_user_tenant_tenant"), "fsuser", type_="foreignkey"
    )
    op.drop_column("fsuser", "user_tenant")
    # ### end Alembic commands ###
