"""Add publish to products

Revision ID: 6d7462bf45e5
Revises: 7ceb8ade2231
Create Date: 2019-03-13 08:21:39.290793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6d7462bf45e5"
down_revision = "7ceb8ade2231"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "product_published",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    op.add_column(
        "product", sa.Column("published_by", sa.Unicode(length=120), nullable=True)
    )
    op.alter_column(
        "product",
        "product_id",
        existing_type=mysql.VARCHAR(length=64),
        type_=sa.Unicode(length=120),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("fk_product_published_by_fsuser"),
        "product",
        "fsuser",
        ["published_by"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_product_published_by_fsuser"), "product", type_="foreignkey"
    )
    op.alter_column(
        "product",
        "product_id",
        existing_type=sa.Unicode(length=120),
        type_=mysql.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_column("product", "published_by")
    op.drop_column("product", "product_published")
    # ### end Alembic commands ###
