"""Add unarchiving details

Revision ID: 6e8f0f158657
Revises: c1a2b3d4e5f6
Create Date: 2026-03-14 06:59:45.287225

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6e8f0f158657"
down_revision = "c1a2b3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("project_unarchived_by", sa.Unicode(length=120), nullable=True),
    )
    op.add_column(
        "project", sa.Column("project_unarchived_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_unarchived_date")
    op.drop_column("project", "project_unarchived_by")
    # ### end Alembic commands ###
