"""Add version and build to ini

Revision ID: 713b00eed9c9
Revises: d9e72a903f87
Create Date: 2020-04-22 14:49:21.947813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713b00eed9c9'
down_revision = 'd9e72a903f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
