"""Add form file table

Revision ID: 72895fa70f4d
Revises: ebd3f0076513
Create Date: 2018-11-24 16:36:41.407258

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "72895fa70f4d"
down_revision = "ebd3f0076513"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediafile",
        sa.Column("file_id", sa.Unicode(length=64), nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("file_name", sa.Unicode(length=120), nullable=True),
        sa.Column("file_udate", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_mediafile_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("file_id", name=op.f("pk_mediafile")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mediafile")
    # ### end Alembic commands ###
