"""Add published by in forms

Revision ID: 759ef01e4971
Revises: 019967069cf0
Create Date: 2018-11-19 10:16:50.779852

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "759ef01e4971"
down_revision = "019967069cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "odkform", sa.Column("form_pubby", sa.Unicode(length=120), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_odkform_form_pubby_fsuser"),
        "odkform",
        "fsuser",
        ["form_pubby"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_odkform_form_pubby_fsuser"), "odkform", type_="foreignkey"
    )
    op.drop_column("odkform", "form_pubby")
    # ### end Alembic commands ###
