"""Disconnect formaccess

Revision ID: 777740410eae
Revises: e46fb3d2e41c
Create Date: 2025-08-25 09:40:10.190766

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "777740410eae"
down_revision = "e46fb3d2e41c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_formaccess_project_id_collaborator", "formaccess", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_formaccess_form_project_odkform", "formaccess", type_="foreignkey"
    )
    op.drop_index("fk_submitter_form1", table_name="formaccess")
    op.drop_index("fk_submitter_form1_idx", table_name="formaccess")
    op.execute("ALTER TABLE formaccess DROP PRIMARY KEY")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_submitter_form1_idx",
        "formaccess",
        ["form_project", "form_id"],
        unique=False,
    )
    op.create_index(
        "fk_submitter_form1", "formaccess", ["form_project", "form_id"], unique=False
    )
    op.create_foreign_key(
        "fk_formaccess_form_project_odkform",
        "formaccess",
        "odkform",
        ["form_project", "form_id"],
        ["project_id", "form_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_formaccess_project_id_collaborator",
        "formaccess",
        "collaborator",
        ["project_id", "coll_id"],
        ["project_id", "coll_id"],
        ondelete="CASCADE",
    )
    op.create_primary_key(
        op.f("pk_formaccess"),
        "formaccess",
        ["project_id", "coll_id", "form_project", "form_id"],
    )

    # ### end Alembic commands ###
