"""Add new primary key to collaborator

Revision ID: 777ad93c6382
Revises: e11efc4fc945
Create Date: 2025-08-25 10:09:34.976511

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "777ad93c6382"
down_revision = "e11efc4fc945"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collaborator",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=True,
    )
    op.alter_column(
        "collaborator",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.alter_column(
        "collaborator",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.create_foreign_key(
        op.f("fk_collaborator_project_id_project"),
        "collaborator",
        "project",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    op.create_primary_key(
        op.f("pk_collaborator"),
        "collaborator",
        ["coll_uuid"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_collaborator_project_id_project"), "collaborator", type_="foreignkey"
    )
    op.alter_column(
        "collaborator",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.alter_column(
        "collaborator",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.alter_column(
        "collaborator",
        "project_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=False,
    )
    op.execute("ALTER TABLE collaborator DROP PRIMARY KEY")
    # ### end Alembic commands ###
