"""Add repository flag

Revision ID: 77d7e4daa88d
Revises: 6b09c0218d0b
Create Date: 2021-01-25 18:37:54.176307

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77d7e4daa88d"
down_revision = "6b09c0218d0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "odkform",
        sa.Column(
            "form_repositorypossible",
            sa.INTEGER(),
            server_default=sa.text("'-1'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_repositorypossible")
    # ### end Alembic commands ###
