"""Initial database

Revision ID: 7881cd04fabc
Revises: 
Create Date: 2017-11-12 19:50:55.616940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7881cd04fabc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_password', sa.String(length=120), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_about', sa.Text(), nullable=True),
    sa.Column('user_cdate', sa.DateTime(), nullable=True),
    sa.Column('user_llogin', sa.DateTime(), nullable=True),
    sa.Column('user_super', sa.Integer(), nullable=True),
    sa.Column('user_logo', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('log',
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('entry_type', sa.Integer(), nullable=True),
    sa.Column('entry_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=op.f('fk_log_user_id_user'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('pk_log')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_log_user_id'), 'log', ['user_id'], unique=False)

    op.create_table('project',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('project_abstract', sa.Text(), nullable=True),
    sa.Column('project_cdate', sa.String(length=45), nullable=True),
    sa.Column('project_creator', sa.String(length=45), nullable=True),
    sa.Column('project_cremail', sa.String(length=45), nullable=True),
    sa.Column('project_contact', sa.String(length=120), nullable=True),
    sa.Column('project_coemail', sa.String(length=45), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=op.f('fk_project_user_id_user'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name=op.f('pk_project')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('datagroup',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('group_desc', sa.Text(), nullable=True),
    sa.Column('group_cdate', sa.DateTime(), nullable=True),
    sa.Column('group_active', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'project_id'], [u'project.user_id', u'project.project_id'], name=op.f('fk_datagroup_user_id_project'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', name=op.f('pk_datagroup')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('datauser',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('duser_id', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_password', sa.String(length=120), nullable=True),
    sa.Column('user_active', sa.Integer(), nullable=True),
    sa.Column('user_cdate', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'project_id'], [u'project.user_id', u'project.project_id'], name=op.f('fk_datauser_user_id_project'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'duser_id', name=op.f('pk_datauser')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('enumerator',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('enum_id', sa.String(length=120), nullable=False),
    sa.Column('enum_name', sa.String(length=120), nullable=True),
    sa.Column('enum_password', sa.String(length=120), nullable=True),
    sa.Column('enum_active', sa.Integer(), nullable=True),
    sa.Column('enum_cdate', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'project_id'], [u'project.user_id', u'project.project_id'], name=op.f('fk_enumerator_user_id_project'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'enum_id', name=op.f('pk_enumerator')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('enumgroup',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('group_desc', sa.Text(), nullable=True),
    sa.Column('group_cdate', sa.DateTime(), nullable=True),
    sa.Column('group_active', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id', 'project_id'], [u'project.user_id', u'project.project_id'], name=op.f('fk_enumgroup_user_id_project'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', name=op.f('pk_enumgroup')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )

    op.create_table('form',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('form_name', sa.String(length=120), nullable=True),
    sa.Column('form_about', sa.Text(), nullable=True),
    sa.Column('form_cdate', sa.DateTime(), nullable=True),
    sa.Column('form_directory', sa.String(length=120), nullable=True),
    sa.Column('form_accsub', sa.Integer(), nullable=True),
    sa.Column('form_public', sa.Integer(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('parent_user', sa.String(length=120), nullable=True),
    sa.Column('parent_project', sa.String(length=12), nullable=True),
    sa.Column('parent_form', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['parent_user', 'parent_project', 'parent_form'], [u'form.user_id', u'form.project_id', u'form.form_id'], name=op.f('fk_form_parent_user_form')),
    sa.ForeignKeyConstraint(['user_id', 'project_id'], [u'project.user_id', u'project.project_id'], name=op.f('fk_form_user_id_project'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'form_id', name=op.f('pk_form')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_form_form1_idx', 'form', ['parent_user', 'parent_project', 'parent_form'], unique=False)

    op.create_table('enumingroup',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('enum_user', sa.String(length=120), nullable=False),
    sa.Column('enum_project', sa.String(length=12), nullable=False),
    sa.Column('enum_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['enum_user', 'enum_project', 'enum_id'], [u'enumerator.user_id', u'enumerator.project_id', u'enumerator.enum_id'], name=op.f('fk_enumingroup_enum_user_enumerator'), ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'group_id'], [u'enumgroup.user_id', u'enumgroup.project_id', u'enumgroup.group_id'], name=op.f('fk_enumingroup_user_id_enumgroup'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', 'enum_user', 'enum_project', 'enum_id', name=op.f('pk_enumingroup')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_enumingroup_enumerator1_idx', 'enumingroup', ['enum_user', 'enum_project', 'enum_id'], unique=False)

    op.create_table('groupaccess',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('form_user', sa.String(length=120), nullable=False),
    sa.Column('form_project', sa.String(length=12), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['form_user', 'form_project', 'form_id'], [u'form.user_id', u'form.project_id', u'form.form_id'], name=op.f('fk_groupaccess_form_user_form')),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'group_id'], [u'datagroup.user_id', u'datagroup.project_id', u'datagroup.group_id'], name=op.f('fk_groupaccess_user_id_datagroup'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', 'form_user', 'form_project', 'form_id', name=op.f('pk_groupaccess')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_groupaccess_form1_idx', 'groupaccess', ['form_user', 'form_project', 'form_id'], unique=False)

    op.create_table('grpsubmitter',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('form_user', sa.String(length=120), nullable=False),
    sa.Column('form_project', sa.String(length=12), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['form_user', 'form_project', 'form_id'], [u'form.user_id', u'form.project_id', u'form.form_id'], name=op.f('fk_grpsubmitter_form_user_form'), ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'group_id'], [u'enumgroup.user_id', u'enumgroup.project_id', u'enumgroup.group_id'], name=op.f('fk_grpsubmitter_user_id_enumgroup'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', 'form_user', 'form_project', 'form_id', name=op.f('pk_grpsubmitter')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_grpsubmitter_form1_idx', 'grpsubmitter', ['form_user', 'form_project', 'form_id'], unique=False)

    op.create_table('submitter',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('enum_id', sa.String(length=120), nullable=False),
    sa.Column('form_user', sa.String(length=120), nullable=False),
    sa.Column('form_project', sa.String(length=12), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['form_user', 'form_project', 'form_id'], [u'form.user_id', u'form.project_id', u'form.form_id'], name=op.f('fk_submitter_form_user_form'), ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'enum_id'], [u'enumerator.user_id', u'enumerator.project_id', u'enumerator.enum_id'], name=op.f('fk_submitter_user_id_enumerator'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'enum_id', 'form_user', 'form_project', 'form_id', name=op.f('pk_submitter')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_submitter_form1_idx', 'submitter', ['form_user', 'form_project', 'form_id'], unique=False)

    op.create_table('useraccess',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('duser_id', sa.String(length=120), nullable=False),
    sa.Column('form_user', sa.String(length=120), nullable=False),
    sa.Column('form_project', sa.String(length=12), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['form_user', 'form_project', 'form_id'], [u'form.user_id', u'form.project_id', u'form.form_id'], name=op.f('fk_useraccess_form_user_form')),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'duser_id'], [u'datauser.user_id', u'datauser.project_id', u'datauser.duser_id'], name=op.f('fk_useraccess_user_id_datauser'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'duser_id', 'form_user', 'form_project', 'form_id', name=op.f('pk_useraccess')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_useraccess_form1_idx', 'useraccess', ['form_user', 'form_project', 'form_id'], unique=False)

    op.create_table('useringroup',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('group_id', sa.String(length=12), nullable=False),
    sa.Column('datauser_user', sa.String(length=120), nullable=False),
    sa.Column('datauser_project', sa.String(length=12), nullable=False),
    sa.Column('datauser_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['datauser_user', 'datauser_project', 'datauser_id'], [u'datauser.user_id', u'datauser.project_id', u'datauser.duser_id'], name=op.f('fk_useringroup_datauser_user_datauser'), ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'project_id', 'group_id'], [u'datagroup.user_id', u'datagroup.project_id', u'datagroup.group_id'], name=op.f('fk_useringroup_user_id_datagroup'), ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'group_id', 'datauser_user', 'datauser_project', 'datauser_id', name=op.f('pk_useringroup')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_useringroup_datauser1_idx', 'useringroup', ['datauser_user', 'datauser_project', 'datauser_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_useringroup_datauser1_idx', table_name='useringroup')
    op.drop_table('useringroup')
    op.drop_index('fk_useraccess_form1_idx', table_name='useraccess')
    op.drop_table('useraccess')
    op.drop_index('fk_submitter_form1_idx', table_name='submitter')
    op.drop_table('submitter')
    op.drop_index('fk_grpsubmitter_form1_idx', table_name='grpsubmitter')
    op.drop_table('grpsubmitter')
    op.drop_index('fk_groupaccess_form1_idx', table_name='groupaccess')
    op.drop_table('groupaccess')
    op.drop_index('fk_enumingroup_enumerator1_idx', table_name='enumingroup')
    op.drop_table('enumingroup')
    op.drop_index('fk_form_form1_idx', table_name='form')
    op.drop_table('form')
    op.drop_table('enumgroup')
    op.drop_table('enumerator')
    op.drop_table('datauser')
    op.drop_table('datagroup')
    op.drop_table('project')
    op.drop_index(op.f('ix_log_user_id'), table_name='log')
    op.drop_table('log')
    op.drop_table('user')
    # ### end Alembic commands ###
