"""Add runtime settings

Revision ID: 7a1f06b526c6
Revises: cd645dcec58a
Create Date: 2019-12-08 12:34:21.955496

"""

import sqlalchemy as sa
from alembic import op

from formshare.models.formshare import JsonEncodedDict

# revision identifiers, used by Alembic.
revision = "7a1f06b526c6"
down_revision = "cd645dcec58a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("settings_key", sa.Unicode(length=64), nullable=False),
        sa.Column("settings_value", JsonEncodedDict(), nullable=True),
        sa.PrimaryKeyConstraint("settings_key", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
