"""Upgrade create.xml files to separate _geopoint

Revision ID: 7a31fe6e7d09
Revises: 0d5b7b290d86
Create Date: 2020-04-21 08:36:48.140455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a31fe6e7d09'
down_revision = '0d5b7b290d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
