"""Disconnect jsonhistory

Revision ID: 7a457467684a
Revises: 777740410eae
Create Date: 2025-08-25 09:47:08.127670

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a457467684a"
down_revision = "777740410eae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_jsonhistory_enum_project_collaborator", "jsonhistory", type_="foreignkey"
    )
    op.drop_index("fk_jsonhistory_enumerator1_idx", table_name="jsonhistory")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_jsonhistory_enumerator1_idx",
        "jsonhistory",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_jsonhistory_enum_project_collaborator",
        "jsonhistory",
        "collaborator",
        ["enum_project", "coll_id"],
        ["project_id", "coll_id"],
    )

    # ### end Alembic commands ###
