"""Add createxmlfile and blocked fields

Revision ID: 7a782be521c1
Revises: 8e6eceeb2678
Create Date: 2019-09-09 09:41:36.760513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a782be521c1'
down_revision = '8e6eceeb2678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odkform', sa.Column('form_blocked', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
    op.add_column('odkform', sa.Column('form_createxmlfile', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odkform', 'form_createxmlfile')
    op.drop_column('odkform', 'form_blocked')
    # ### end Alembic commands ###
