"""Add active project

Revision ID: 80c172946a90
Revises: 8c35ff4b0bad
Create Date: 2018-09-07 14:48:13.230057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80c172946a90"
down_revision = "8c35ff4b0bad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userproject",
        sa.Column(
            "project_active", sa.INTEGER(), server_default=sa.text("'1'"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userproject", "project_active")
    # ### end Alembic commands ###
