"""Cascade delete from user and project to userproject

Revision ID: 87f2a566911d
Revises: 74c6bb8ace79
Create Date: 2018-11-09 14:39:01.293252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f2a566911d'
down_revision = '74c6bb8ace79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_userproject_user_id_fsuser', 'userproject', type_='foreignkey')
    op.drop_constraint('fk_userproject_project_id_project', 'userproject', type_='foreignkey')
    op.create_foreign_key(op.f('fk_userproject_user_id_fsuser'), 'userproject', 'fsuser', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_userproject_project_id_project'), 'userproject', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_userproject_project_id_project'), 'userproject', type_='foreignkey')
    op.drop_constraint(op.f('fk_userproject_user_id_fsuser'), 'userproject', type_='foreignkey')
    op.create_foreign_key('fk_userproject_project_id_project', 'userproject', 'project', ['project_id'], ['project_id'])
    op.create_foreign_key('fk_userproject_user_id_fsuser', 'userproject', 'fsuser', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
