"""Add command to json log

Revision ID: 8ad53c7df321
Revises: 30b6bc6b6875
Create Date: 2020-09-04 07:41:17.435130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ad53c7df321"
down_revision = "30b6bc6b6875"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jsonlog", sa.Column("command_executed", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jsonlog", "command_executed")
    # ### end Alembic commands ###
