"""Remove task table

Revision ID: 8dea2dd6d509
Revises: 303c3b7100f5
Create Date: 2019-03-27 15:32:49.361973

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8dea2dd6d509"
down_revision = "303c3b7100f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("task_id", mysql.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
