"""Add merge errors field

Revision ID: 8e6eceeb2678
Revises: 1490c071fb7e
Create Date: 2019-09-07 15:39:31.236777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e6eceeb2678"
down_revision = "1490c071fb7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "odkform", sa.Column("form_mergerrors", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_mergerrors")
    # ### end Alembic commands ###
