"""Add file link

Revision ID: 9498f8e802f6
Revises: 72895fa70f4d
Create Date: 2018-11-24 22:30:02.050134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9498f8e802f6'
down_revision = '72895fa70f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediafile', sa.Column('file_url', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediafile', 'file_url')
    # ### end Alembic commands ###
