"""Add archived field to project

Revision ID: 9745b2b4de42
Revises: 6f77a7a65630
Create Date: 2026-02-14 16:33:21.525370

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9745b2b4de42"
down_revision = "0bc56c77ec06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "project_archived",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_archived")
    # ### end Alembic commands ###
