"""Remove old fixed roles

Revision ID: 9ed435d735c4
Revises: a5b3b7c5ec81
Create Date: 2025-08-24 07:21:55.409311

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9ed435d735c4"
down_revision = "a5b3b7c5ec81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fsuser", "user_can_projects")
    op.drop_column("fsuser", "user_can_forms")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fsuser",
        sa.Column(
            "user_can_forms",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "fsuser",
        sa.Column(
            "user_can_projects",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
