"""Add json file to form

Revision ID: a38268564115
Revises: e3f8a1c67b18
Create Date: 2019-02-15 14:19:43.811530

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a38268564115"
down_revision = "e3f8a1c67b18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "odkform", sa.Column("form_jsonfile", sa.UnicodeText(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("odkform", "form_jsonfile")
    # ### end Alembic commands ###
