"""Add new indexes to submission

Revision ID: a9e848e4c122
Revises: dbf704f483e3
Create Date: 2025-08-24 10:48:28.131849

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a9e848e4c122"
down_revision = "dbf704f483e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_submission_fast",
        "submission",
        ["project_id", "form_id", "original_md5sum", "sameas", "submission_id"],
        unique=False,
    )
    op.create_index(
        "idx_submission_last",
        "submission",
        ["project_id", "form_id", "sameas", "submission_dtime"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_submission_last", table_name="submission")
    op.drop_index("idx_submission_fast", table_name="submission")
    # ### end Alembic commands ###
