"""Few changes in user table

Revision ID: aaf2afeeea24
Revises: 6088fadfc4d9
Create Date: 2017-12-01 19:44:00.811260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf2afeeea24'
down_revision = '6088fadfc4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_logo')
    op.alter_column('user', 'user_super', server_default='0')
    op.alter_column('user', 'user_apikey', type_=sa.VARCHAR(64))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_logo', mysql.TEXT(), nullable=True))
    op.alter_column('user', 'user_apikey', type_=sa.TEXT())
    op.alter_column('user', 'user_super', server_default=None)
    # ### end Alembic commands ###
