"""Cascade the delete of merged forms

Revision ID: b0d6a2d89fc7
Revises: 4fd6a929c8b9
Create Date: 2020-12-27 10:23:59.358579

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0d6a2d89fc7"
down_revision = "4fd6a929c8b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_odkform_parent_project_odkform", "odkform", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_odkform_parent_project_odkform"),
        "odkform",
        "odkform",
        ["parent_project", "parent_form"],
        ["project_id", "form_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_odkform_parent_project_odkform"), "odkform", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_odkform_parent_project_odkform",
        "odkform",
        "odkform",
        ["parent_project", "parent_form"],
        ["project_id", "form_id"],
    )
    # ### end Alembic commands ###
