"""Add archived by and date

Revision ID: b3711f9c82a0
Revises: 9745b2b4de42
Create Date: 2026-02-16 09:40:47.288742

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b3711f9c82a0"
down_revision = "9745b2b4de42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("project_archived_by", sa.Unicode(length=120), nullable=True),
    )
    op.add_column(
        "project", sa.Column("project_archived_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_archived_date")
    op.drop_column("project", "project_archived_by")
    # ### end Alembic commands ###
