"""Remove table of workspace access

Revision ID: b476703716fc
Revises: 58d91afe341f
Create Date: 2025-09-17 13:48:10.488422

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b476703716fc"
down_revision = "58d91afe341f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userworkspace")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userworkspace",
        sa.Column(
            "workspace_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
            nullable=False,
        ),
        sa.Column("access_date", mysql.DATETIME(), nullable=True),
        sa.Column("access_type", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fsuser.user_id"],
            name="fk_userworkspace_user_id_fsuser",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["fsuser.user_id"],
            name="fk_userworkspace_workspace_id_fsuser",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
