"""Increase schema to 64 chars

Revision ID: b9a8461b1c66
Revises: 7f93d6af79d0
Create Date: 2019-03-28 11:22:13.081205

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9a8461b1c66"
down_revision = "7f93d6af79d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "odkform",
        "form_schema",
        existing_type=mysql.VARCHAR(length=13),
        type_=sa.Unicode(length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "odkform",
        "form_schema",
        existing_type=sa.Unicode(length=64),
        type_=mysql.VARCHAR(length=13),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
