"""Remove same as fields and replace them by share across projets

Revision ID: be332836941b
Revises: d42cd7ce9acf
Create Date: 2018-08-24 15:02:00.277160

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "be332836941b"
down_revision = "d42cd7ce9acf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator", sa.Column("coll_prjshare", sa.INTEGER(), nullable=True)
    )
    op.drop_constraint(
        "fk_collaborator_samas_project_collaborator", "collaborator", type_="foreignkey"
    )
    op.drop_index("fk_enumerator_enumerator1_idx", table_name="collaborator")
    op.drop_column("collaborator", "sameas_coll")
    op.drop_column("collaborator", "samas_project")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator",
        sa.Column("samas_project", mysql.VARCHAR(length=64), nullable=True),
    )
    op.add_column(
        "collaborator",
        sa.Column("sameas_coll", mysql.VARCHAR(length=120), nullable=True),
    )
    op.create_index(
        "fk_enumerator_enumerator1_idx",
        "collaborator",
        ["samas_project", "sameas_coll"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_collaborator_samas_project_collaborator",
        "collaborator",
        "collaborator",
        ["samas_project", "sameas_coll"],
        ["project_id", "coll_id"],
        ondelete="CASCADE",
    )
    op.drop_column("collaborator", "coll_prjshare")
    # ### end Alembic commands ###
