"""Link again formaccess

Revision ID: c481201868bb
Revises: 5f627adcc4a5
Create Date: 2025-08-25 10:33:08.414842

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c481201868bb"
down_revision = "5f627adcc4a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_submitter_collaborator", "formaccess", ["coll_uuid"], unique=False
    )
    op.create_index(
        "fk_submitter_project", "formaccess", ["form_project", "form_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_formaccess_form_project_odkform"),
        "formaccess",
        "odkform",
        ["form_project", "form_id"],
        ["project_id", "form_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_formaccess_coll_uuid_collaborator"),
        "formaccess",
        "collaborator",
        ["coll_uuid"],
        ["coll_uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_formaccess_coll_uuid_collaborator"), "formaccess", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_formaccess_form_project_odkform"), "formaccess", type_="foreignkey"
    )
    op.drop_index("fk_submitter_project", table_name="formaccess")
    op.drop_index("fk_submitter_collaborator", table_name="formaccess")
    # ### end Alembic commands ###
