"""Change extra to extras

Revision ID: cb71f27114e5
Revises: 213734b12f44
Create Date: 2018-09-10 10:19:09.100910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb71f27114e5'
down_revision = '213734b12f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborator', sa.Column('extras', sa.UnicodeText(), nullable=True))
    op.drop_column('collaborator', 'extra')
    op.add_column('collgroup', sa.Column('extras', sa.UnicodeText(), nullable=True))
    op.drop_column('collgroup', 'extra')
    op.add_column('fsuser', sa.Column('extras', sa.UnicodeText(), nullable=True))
    op.drop_column('fsuser', 'extra')
    op.add_column('odkform', sa.Column('extras', sa.UnicodeText(), nullable=True))
    op.drop_column('odkform', 'extra')
    op.add_column('project', sa.Column('extras', sa.UnicodeText(), nullable=True))
    op.drop_column('project', 'extra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('project', 'extras')
    op.add_column('odkform', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('odkform', 'extras')
    op.add_column('fsuser', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('fsuser', 'extras')
    op.add_column('collgroup', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('collgroup', 'extras')
    op.add_column('collaborator', sa.Column('extra', mysql.TEXT(), nullable=True))
    op.drop_column('collaborator', 'extras')
    # ### end Alembic commands ###
