"""Add API key to assistants

Revision ID: cd645dcec58a
Revises: 3932ad37cc0b
Create Date: 2019-12-01 20:10:28.981417

"""
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from formshare.models.formshare import Collaborator
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "cd645dcec58a"
down_revision = "3932ad37cc0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator", sa.Column("coll_apikey", sa.Unicode(length=64), nullable=True)
    )
    # ### end Alembic commands ###
    session = Session(bind=op.get_bind())

    collaborators = session.query(
        Collaborator.project_id, Collaborator.coll_id, Collaborator.coll_password
    ).all()
    for collaborator in collaborators:
        unique_id = str(uuid4())
        session.query(Collaborator).filter(
            Collaborator.project_id == collaborator.project_id
        ).filter(Collaborator.coll_id == collaborator.coll_id).update(
            {"coll_apikey": unique_id}
        )
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collaborator", "coll_apikey")
    # ### end Alembic commands ###
