"""Make project and collaborator unique

Revision ID: cf90ef87eb87
Revises: f1387225be0e
Create Date: 2025-08-25 14:30:59.071967

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf90ef87eb87"
down_revision = "f1387225be0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "unique_project_coll_id", "collaborator", ["project_id", "coll_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_project_coll_id", table_name="collaborator")
    # ### end Alembic commands ###
