"""Add control for public/private projects and forms

Revision ID: d0827785318a
Revises: be332836941b
Create Date: 2018-09-05 10:50:48.846159

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d0827785318a"
down_revision = "be332836941b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("odkform", sa.Column("form_public", sa.INTEGER(), nullable=True))
    op.add_column("project", sa.Column("project_public", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "project_public")
    op.drop_column("odkform", "form_public")
    # ### end Alembic commands ###
