"""Add role and userrole table

Revision ID: d3730e1f9afb
Revises: 03441e0d7d31
Create Date: 2025-08-16 11:20:49.000495

"""

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = "d3730e1f9afb"
down_revision = "03441e0d7d31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("role_id", sa.Unicode(length=64), nullable=False),
        sa.Column("role_name", sa.Unicode(length=120), nullable=True),
        sa.PrimaryKeyConstraint("role_id", name=op.f("pk_role")),
    )

    # Insert initial data
    conn = op.get_bind()
    role_table = sa.table(
        "role",
        sa.column("role_id", sa.Unicode(length=64)),
        sa.column("role_name", sa.Unicode(length=120)),
    )

    conn.execute(
        role_table.insert(),
        [
            {"role_id": "can_projects", "role_name": "Create projects"},
            {"role_id": "can_forms", "role_name": "Create forms"},
        ],
    )

    op.create_table(
        "userrole",
        sa.Column("user_id", sa.Unicode(length=120), nullable=False),
        sa.Column("role_id", sa.Unicode(length=64), nullable=False),
        sa.Column("grant_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.role_id"],
            name=op.f("fk_userrole_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fsuser.user_id"],
            name=op.f("fk_userrole_user_id_fsuser"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_userrole")),
    )
    op.create_index(op.f("ix_userrole_role_id"), "userrole", ["role_id"], unique=False)

    conn.execute(
        sa.text("""
            INSERT INTO userrole (user_id, role_id, grant_date)
            SELECT user_id, 'can_projects', :grant_date
            FROM fsuser
            WHERE user_can_projects = 1
            """),
        {"grant_date": datetime.utcnow()},
    )

    conn.execute(
        sa.text("""
            INSERT INTO userrole (user_id, role_id, grant_date)
            SELECT user_id, 'can_forms', :grant_date
            FROM fsuser
            WHERE user_can_forms = 1
            """),
        {"grant_date": datetime.utcnow()},
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userrole")
    op.drop_table("role")
    # ### end Alembic commands ###
