"""Remove separate group table

Revision ID: d79b5450910f
Revises: 439e75118151
Create Date: 2019-08-31 23:41:39.084117

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d79b5450910f"
down_revision = "439e75118151"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sepsection")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sepsection",
        sa.Column("project_id", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("form_id", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("table_name", mysql.VARCHAR(length=120), nullable=False),
        sa.Column("section_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column("section_name", mysql.VARCHAR(length=120), nullable=True),
        sa.Column("section_desc", mysql.TEXT(), nullable=True),
        sa.Column(
            "section_order",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id", "table_name"],
            ["septable.project_id", "septable.form_id", "septable.table_name"],
            name="fk_sepsection_project_id_septable",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "form_id", "table_name", "section_id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
