"""Add max submissions to user

Revision ID: d90cdbd36cae
Revises: 97cf65221719
Create Date: 2026-08-06 16:05:03.460565

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d90cdbd36cae"
down_revision = "97cf65221719"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fsuser",
        sa.Column(
            "user_max_submissions",
            sa.INTEGER(),
            server_default=sa.text("'500'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fsuser", "user_max_submissions")
    # ### end Alembic commands ###
