"""Initial version

Revision ID: d9a26c485a70
Revises: 
Create Date: 2018-07-25 10:57:21.207360

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d9a26c485a70"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collaboratorlog",
        sa.Column("log_entry", sa.Unicode(length=64), nullable=False),
        sa.Column("log_datetime", sa.DateTime(), nullable=True),
        sa.Column("access_type", sa.INTEGER(), nullable=True),
        sa.Column("interface", sa.INTEGER(), nullable=True),
        sa.Column("action", sa.INTEGER(), nullable=True),
        sa.Column("userid", sa.Unicode(length=255), nullable=True),
        sa.Column("org", sa.Unicode(length=32), nullable=True),
        sa.Column("project", sa.Unicode(length=32), nullable=True),
        sa.Column("form", sa.Unicode(length=120), nullable=True),
        sa.Column("collaborator", sa.Unicode(length=32), nullable=True),
        sa.Column("logid", sa.Unicode(length=64), nullable=True),
        sa.Column("commitid", sa.Unicode(length=12), nullable=True),
        sa.Column("schemaid", sa.Unicode(length=13), nullable=True),
        sa.Column("tableid", sa.Unicode(length=120), nullable=True),
        sa.PrimaryKeyConstraint("log_entry", name=op.f("pk_collaboratorlog")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "fsuser",
        sa.Column("user_id", sa.Unicode(length=120), nullable=False),
        sa.Column("user_name", sa.Unicode(length=120), nullable=True),
        sa.Column("user_password", sa.Unicode(length=120), nullable=True),
        sa.Column("user_about", sa.UnicodeText(), nullable=True),
        sa.Column("user_cdate", sa.DateTime(), nullable=True),
        sa.Column("user_llogin", sa.DateTime(), nullable=True),
        sa.Column(
            "user_super", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
        sa.Column("extra", sa.UnicodeText(), nullable=True),
        sa.Column("tags", sa.UnicodeText(), nullable=True),
        sa.Column(
            "user_active", sa.INTEGER(), server_default=sa.text("'1'"), nullable=True
        ),
        sa.Column("user_apikey", sa.Unicode(length=64), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_fsuser")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "project",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("project_name", sa.UnicodeText(), nullable=True),
        sa.Column("project_abstract", sa.UnicodeText(), nullable=True),
        sa.Column("project_cdate", sa.DateTime(), nullable=True),
        sa.Column("project_creator", sa.Unicode(length=45), nullable=True),
        sa.Column("project_cremail", sa.Unicode(length=45), nullable=True),
        sa.Column("project_contact", sa.Unicode(length=120), nullable=True),
        sa.Column("project_coemail", sa.Unicode(length=45), nullable=True),
        sa.Column("extra", sa.UnicodeText(), nullable=True),
        sa.Column("tags", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "userlog",
        sa.Column("log_entry", sa.Unicode(length=64), nullable=False),
        sa.Column("log_datetime", sa.DateTime(), nullable=True),
        sa.Column("access_type", sa.INTEGER(), nullable=True),
        sa.Column("tableid", sa.Unicode(length=45), nullable=True),
        sa.Column("action", sa.INTEGER(), nullable=True),
        sa.Column("userid", sa.Unicode(length=255), nullable=True),
        sa.Column("org", sa.Unicode(length=32), nullable=True),
        sa.Column("project", sa.Unicode(length=32), nullable=True),
        sa.Column("form", sa.Unicode(length=120), nullable=True),
        sa.Column("collaborator", sa.Unicode(length=32), nullable=True),
        sa.Column("groupid", sa.Unicode(length=12), nullable=True),
        sa.Column("septable", sa.Unicode(length=120), nullable=True),
        sa.Column("sepsection", sa.Unicode(length=12), nullable=True),
        sa.Column("sepitem", sa.Unicode(length=120), nullable=True),
        sa.PrimaryKeyConstraint("log_entry", name=op.f("pk_userlog")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "collaborator",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.Column("coll_name", sa.Unicode(length=120), nullable=True),
        sa.Column("coll_password", sa.Unicode(length=120), nullable=True),
        sa.Column("coll_active", sa.INTEGER(), nullable=True),
        sa.Column("coll_cdate", sa.DateTime(), nullable=True),
        sa.Column("coll_email", sa.UnicodeText(), nullable=True),
        sa.Column("coll_telephone", sa.Unicode(length=120), nullable=True),
        sa.Column("extra", sa.UnicodeText(), nullable=True),
        sa.Column("tags", sa.UnicodeText(), nullable=True),
        sa.Column("samas_project", sa.Unicode(length=64), nullable=True),
        sa.Column("sameas_coll", sa.Unicode(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_collaborator_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["samas_project", "sameas_coll"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_collaborator_samas_project_collaborator"),
        ),
        sa.PrimaryKeyConstraint("project_id", "coll_id", name=op.f("pk_collaborator")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_enumerator_enumerator1_idx",
        "collaborator",
        ["samas_project", "sameas_coll"],
        unique=False,
    )
    op.create_table(
        "collgroup",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("group_id", sa.Unicode(length=12), nullable=False),
        sa.Column("group_desc", sa.UnicodeText(), nullable=True),
        sa.Column("group_cdate", sa.DateTime(), nullable=True),
        sa.Column("group_active", sa.INTEGER(), nullable=True),
        sa.Column("extra", sa.UnicodeText(), nullable=True),
        sa.Column("tags", sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_collgroup_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "group_id", name=op.f("pk_collgroup")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "odkform",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("form_name", sa.Unicode(length=120), nullable=True),
        sa.Column("form_cdate", sa.DateTime(), nullable=True),
        sa.Column("form_directory", sa.Unicode(length=120), nullable=True),
        sa.Column("form_schema", sa.Unicode(length=13), nullable=True),
        sa.Column("form_accsub", sa.INTEGER(), nullable=True),
        sa.Column(
            "form_testing", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
        sa.Column(
            "form_incversion",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
        sa.Column("parent_project", sa.Unicode(length=64), nullable=True),
        sa.Column("parent_form", sa.Unicode(length=120), nullable=True),
        sa.Column("form_stage", sa.INTEGER(), nullable=True),
        sa.Column("form_pkey", sa.Unicode(length=120), nullable=True),
        sa.Column("form_deflang", sa.Unicode(length=120), nullable=True),
        sa.Column("form_yesno", sa.Unicode(length=120), nullable=True),
        sa.Column("form_othlangs", sa.UnicodeText(), nullable=True),
        sa.Column("form_sepfile", sa.UnicodeText(), nullable=True),
        sa.Column("form_xlsfile", sa.UnicodeText(), nullable=True),
        sa.Column("form_xmlfile", sa.UnicodeText(), nullable=True),
        sa.Column("extra", sa.UnicodeText(), nullable=True),
        sa.Column("tags", sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_project", "parent_form"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_odkform_parent_project_odkform"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_odkform_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "form_id", name=op.f("pk_odkform")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_form_form1_idx", "odkform", ["parent_project", "parent_form"], unique=False
    )
    op.create_table(
        "userproject",
        sa.Column("user_id", sa.Unicode(length=120), nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("access_type", sa.INTEGER(), nullable=True),
        sa.Column("access_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
            name=op.f("fk_userproject_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["fsuser.user_id"], name=op.f("fk_userproject_user_id_fsuser")
        ),
        sa.PrimaryKeyConstraint("user_id", "project_id", name=op.f("pk_userproject")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_userproject_project_id"), "userproject", ["project_id"], unique=False
    )
    op.create_table(
        "collingroup",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("group_id", sa.Unicode(length=12), nullable=False),
        sa.Column("enum_project", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.Column("coll_privileges", sa.INTEGER(), nullable=True),
        sa.Column("join_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enum_project", "coll_id"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_collingroup_enum_project_collaborator"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "group_id"],
            ["collgroup.project_id", "collgroup.group_id"],
            name=op.f("fk_collingroup_project_id_collgroup"),
            ondelete="NO ACTION",
            onupdate="NO ACTION",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "group_id",
            "enum_project",
            "coll_id",
            name=op.f("pk_collingroup"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_enumingroup_enumerator1",
        "collingroup",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_index(
        "fk_enumingroup_enumerator1_idx",
        "collingroup",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_table(
        "formaccess",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.Column("form_project", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("coll_privileges", sa.INTEGER(), nullable=True),
        sa.Column("access_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_project", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_formaccess_form_project_odkform"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "coll_id"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_formaccess_project_id_collaborator"),
            ondelete="NO ACTION",
            onupdate="NO ACTION",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "coll_id",
            "form_project",
            "form_id",
            name=op.f("pk_formaccess"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_submitter_form1", "formaccess", ["form_project", "form_id"], unique=False
    )
    op.create_index(
        "fk_submitter_form1_idx",
        "formaccess",
        ["form_project", "form_id"],
        unique=False,
    )
    op.create_table(
        "formgrpaccess",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("group_id", sa.Unicode(length=12), nullable=False),
        sa.Column("form_project", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("access_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_project", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_formgrpaccess_form_project_odkform"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "group_id"],
            ["collgroup.project_id", "collgroup.group_id"],
            name=op.f("fk_formgrpaccess_project_id_collgroup"),
            ondelete="NO ACTION",
            onupdate="NO ACTION",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "group_id",
            "form_project",
            "form_id",
            name=op.f("pk_formgrpaccess"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_grpsubmitter_form1",
        "formgrpaccess",
        ["form_project", "form_id"],
        unique=False,
    )
    op.create_index(
        "fk_grpsubmitter_form1_idx",
        "formgrpaccess",
        ["form_project", "form_id"],
        unique=False,
    )
    op.create_table(
        "jsonlog",
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("log_id", sa.Unicode(length=64), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("json_file", sa.UnicodeText(), nullable=True),
        sa.Column("log_file", sa.UnicodeText(), nullable=True),
        sa.Column("status", sa.INTEGER(), nullable=True),
        sa.Column("enum_project", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["enum_project", "coll_id"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_jsonlog_enum_project_collaborator"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_jsonlog_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "form_id", "project_id", "log_id", name=op.f("pk_jsonlog")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_jsonlog_enumerator1_idx",
        "jsonlog",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_index(
        "fk_jsonlog_form1_idx", "jsonlog", ["project_id", "form_id"], unique=False
    )
    op.create_table(
        "septable",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("table_name", sa.Unicode(length=120), nullable=False),
        sa.Column("table_desc", sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_septable_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "form_id", "table_name", name=op.f("pk_septable")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "submission",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("submission_id", sa.Unicode(length=64), nullable=False),
        sa.Column("submission_dtime", sa.DateTime(), nullable=True),
        sa.Column("submission_status", sa.INTEGER(), nullable=True),
        sa.Column("enum_project", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.Column("md5sum", sa.Unicode(length=120), nullable=True),
        sa.Column("sameas", sa.Unicode(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["enum_project", "coll_id"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_submission_enum_project_collaborator"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_submission_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "form_id", "submission_id", name=op.f("pk_submission")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_submission_enumerator1_idx",
        "submission",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_index(
        "fk_submission_form1_idx", "submission", ["project_id", "form_id"], unique=False
    )
    op.create_table(
        "jsonhistory",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("log_id", sa.Unicode(length=64), nullable=False),
        sa.Column("log_sequence", sa.Unicode(length=12), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("log_action", sa.INTEGER(), nullable=True),
        sa.Column("log_commit", sa.Unicode(length=12), nullable=True),
        sa.Column("log_notes", sa.UnicodeText(), nullable=True),
        sa.Column("enum_project", sa.Unicode(length=64), nullable=False),
        sa.Column("coll_id", sa.Unicode(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["enum_project", "coll_id"],
            ["collaborator.project_id", "collaborator.coll_id"],
            name=op.f("fk_jsonhistory_enum_project_collaborator"),
        ),
        sa.ForeignKeyConstraint(
            ["form_id", "project_id", "log_id"],
            ["jsonlog.form_id", "jsonlog.project_id", "jsonlog.log_id"],
            name=op.f("fk_jsonhistory_form_id_jsonlog"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "form_id",
            "log_id",
            "log_sequence",
            name=op.f("pk_jsonhistory"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_jsonhistory_enumerator1_idx",
        "jsonhistory",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_index(
        "fk_jsonhistory_jsonlog1_idx",
        "jsonhistory",
        ["form_id", "project_id", "log_id"],
        unique=False,
    )
    op.create_table(
        "sepsection",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("table_name", sa.Unicode(length=120), nullable=False),
        sa.Column("section_id", sa.Unicode(length=12), nullable=False),
        sa.Column("section_name", sa.Unicode(length=120), nullable=True),
        sa.Column("section_desc", sa.UnicodeText(), nullable=True),
        sa.Column("section_order", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id", "table_name"],
            ["septable.project_id", "septable.form_id", "septable.table_name"],
            name=op.f("fk_sepsection_project_id_septable"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "form_id",
            "table_name",
            "section_id",
            name=op.f("pk_sepsection"),
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "sepitems",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("table_name", sa.Unicode(length=120), nullable=False),
        sa.Column("item_name", sa.Unicode(length=120), nullable=False),
        sa.Column("item_desc", sa.UnicodeText(), nullable=True),
        sa.Column("item_xmlcode", sa.UnicodeText(), nullable=True),
        sa.Column("item_notdisplay", sa.INTEGER(), nullable=True),
        sa.Column("item_order", sa.INTEGER(), nullable=True),
        sa.Column("section_project", sa.Unicode(length=64), nullable=False),
        sa.Column("section_form", sa.Unicode(length=120), nullable=False),
        sa.Column("section_table", sa.Unicode(length=120), nullable=False),
        sa.Column("section_id", sa.Unicode(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id", "table_name"],
            ["septable.project_id", "septable.form_id", "septable.table_name"],
            name=op.f("fk_sepitems_project_id_septable"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_project", "section_form", "section_table", "section_id"],
            [
                "sepsection.project_id",
                "sepsection.form_id",
                "sepsection.table_name",
                "sepsection.section_id",
            ],
            name=op.f("fk_sepitems_section_project_sepsection"),
            ondelete="NO ACTION",
            onupdate="NO ACTION",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "form_id", "table_name", "item_name", name=op.f("pk_sepitems")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_sepitems_sepsection1_idx",
        "sepitems",
        ["section_project", "section_form", "section_table", "section_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("fk_sepitems_sepsection1_idx", table_name="sepitems")
    op.drop_table("sepitems")
    op.drop_table("sepsection")
    op.drop_index("fk_jsonhistory_jsonlog1_idx", table_name="jsonhistory")
    op.drop_index("fk_jsonhistory_enumerator1_idx", table_name="jsonhistory")
    op.drop_table("jsonhistory")
    op.drop_index("fk_submission_form1_idx", table_name="submission")
    op.drop_index("fk_submission_enumerator1_idx", table_name="submission")
    op.drop_table("submission")
    op.drop_table("septable")
    op.drop_index("fk_jsonlog_form1_idx", table_name="jsonlog")
    op.drop_index("fk_jsonlog_enumerator1_idx", table_name="jsonlog")
    op.drop_table("jsonlog")
    op.drop_index("fk_grpsubmitter_form1_idx", table_name="formgrpaccess")
    op.drop_index("fk_grpsubmitter_form1", table_name="formgrpaccess")
    op.drop_table("formgrpaccess")
    op.drop_index("fk_submitter_form1_idx", table_name="formaccess")
    op.drop_index("fk_submitter_form1", table_name="formaccess")
    op.drop_table("formaccess")
    op.drop_index("fk_enumingroup_enumerator1_idx", table_name="collingroup")
    op.drop_index("fk_enumingroup_enumerator1", table_name="collingroup")
    op.drop_table("collingroup")
    op.drop_index(op.f("ix_userproject_project_id"), table_name="userproject")
    op.drop_table("userproject")
    op.drop_index("fk_form_form1_idx", table_name="odkform")
    op.drop_table("odkform")
    op.drop_table("collgroup")
    op.drop_index("fk_enumerator_enumerator1_idx", table_name="collaborator")
    op.drop_table("collaborator")
    op.drop_table("userlog")
    op.drop_table("project")
    op.drop_table("fsuser")
    op.drop_table("collaboratorlog")
    # ### end Alembic commands ###
