"""Add coll_uuid to all tables related to assistant

Revision ID: dab4636d0433
Revises: a9e848e4c122
Create Date: 2025-08-24 11:10:53.068439

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dab4636d0433"
down_revision = "a9e848e4c122"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "collingroup", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    op.add_column(
        "formaccess", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    op.add_column(
        "jsonhistory", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    op.add_column(
        "jsonlog", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    op.add_column(
        "submission", sa.Column("coll_uuid", sa.Unicode(length=120), nullable=True)
    )
    conn = op.get_bind()
    # Update collingroup
    conn.execute(
        "UPDATE collingroup "
        "LEFT JOIN collaborator "
        "ON collingroup.enum_project = collaborator.project_id "
        "AND collingroup.coll_id = collaborator.coll_id "
        "SET collingroup.coll_uuid = collaborator.coll_uuid"
    )

    # Update formaccess
    conn.execute(
        "UPDATE formaccess "
        "LEFT JOIN collaborator "
        "ON formaccess.project_id = collaborator.project_id "
        "AND formaccess.coll_id = collaborator.coll_id "
        "SET formaccess.coll_uuid = collaborator.coll_uuid"
    )

    # Update jsonhistory
    conn.execute(
        "UPDATE jsonhistory "
        "LEFT JOIN collaborator "
        "ON jsonhistory.enum_project = collaborator.project_id "
        "AND jsonhistory.coll_id = collaborator.coll_id "
        "SET jsonhistory.coll_uuid = collaborator.coll_uuid"
    )

    # Update jsonlog
    conn.execute(
        "UPDATE jsonlog "
        "LEFT JOIN collaborator "
        "ON jsonlog.enum_project = collaborator.project_id "
        "AND jsonlog.coll_id = collaborator.coll_id "
        "SET jsonlog.coll_uuid = collaborator.coll_uuid"
    )

    # Update submission
    conn.execute(
        "UPDATE submission "
        "LEFT JOIN collaborator "
        "ON submission.enum_project = collaborator.project_id "
        "AND submission.coll_id = collaborator.coll_id "
        "SET submission.coll_uuid = collaborator.coll_uuid"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "coll_uuid")
    op.drop_column("jsonlog", "coll_uuid")
    op.drop_column("jsonhistory", "coll_uuid")
    op.drop_column("formaccess", "coll_uuid")
    op.drop_column("collingroup", "coll_uuid")
    # ### end Alembic commands ###
