"""Link an assistant to an user

Revision ID: dbf704f483e3
Revises: 40148cb4bf3a
Create Date: 2025-08-24 10:38:42.543102

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dbf704f483e3"
down_revision = "40148cb4bf3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator", sa.Column("linked_user", sa.Unicode(length=120), nullable=True)
    )
    op.create_index(
        op.f("ix_collaborator_linked_user"),
        "collaborator",
        ["linked_user"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_collaborator_linked_user_fsuser"),
        "collaborator",
        "fsuser",
        ["linked_user"],
        ["user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_column("collaborator", "linked_user")
    # ### end Alembic commands ###
