"""Add main tenant field

Revision ID: dd3da02417b1
Revises: d3730e1f9afb
Create Date: 2025-08-17 15:57:29.601300

"""

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = "dd3da02417b1"
down_revision = "d3730e1f9afb"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column("tenant", "tenat_active")
    op.add_column(
        "tenant",
        sa.Column(
            "tenant_active", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    op.add_column(
        "tenant",
        sa.Column(
            "tenant_main", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    conn = op.get_bind()
    tenant_table = sa.table(
        "tenant",
        sa.column("tenant_id", sa.Unicode(length=120)),
        sa.column("tenant_name", sa.Unicode(length=120)),
        sa.column("tenant_cdate", sa.DateTime()),
        sa.column("tenat_active", sa.INTEGER()),
        sa.column("tenant_main", sa.INTEGER()),
    )

    conn.execute(
        tenant_table.insert(),
        [
            {
                "tenant_id": "main",
                "tenant_name": "Main",
                "tenant_cdate": datetime.datetime.now(),
                "tenant_active": 1,
                "tenant_main": 1,
            },
        ],
    )

    conn.execute(sa.text("UPDATE fsuser SET user_tenant = 'main'"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant", "tenant_main")
    op.drop_column("tenant", "tenant_active")
    op.add_column(
        "tenant",
        sa.Column(
            "tenat_active", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE fsuser SET user_tenant = null"))
    # ### end Alembic commands ###
