"""Add new primary key to collingroup

Revision ID: e46fb3d2e41c
Revises: 34b3241b325d
Create Date: 2025-08-25 09:16:14.022937

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e46fb3d2e41c"
down_revision = "34b3241b325d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collingroup",
        "enum_project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=True,
    )
    op.alter_column(
        "collingroup",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.alter_column(
        "collingroup",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.create_primary_key(
        op.f("pk_collingroup"),
        "collingroup",
        ["project_id", "group_id", "coll_uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collingroup",
        "coll_uuid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=True,
    )
    op.alter_column(
        "collingroup",
        "coll_id",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=120
        ),
        nullable=False,
    )
    op.alter_column(
        "collingroup",
        "enum_project",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=False,
    )
    op.execute("ALTER TABLE collingroup DROP PRIMARY KEY")
