"""Add settings at form level

Revision ID: e6574044279f
Revises: e7b061b1e13c
Create Date: 2019-12-09 19:04:14.491917

"""
import sqlalchemy as sa
from alembic import op

from formshare.models.formshare import JsonEncodedDict

# revision identifiers, used by Alembic.
revision = "e6574044279f"
down_revision = "e7b061b1e13c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formsettings",
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("settings_key", sa.Unicode(length=64), nullable=False),
        sa.Column("settings_value", JsonEncodedDict(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_formsettings_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "form_id", "settings_key", name=op.f("pk_formsettings")
        ),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "fk_settings_form1_idx", "formsettings", ["project_id", "form_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("fk_settings_form1_idx", table_name="formsettings")
    op.drop_table("formsettings")
    # ### end Alembic commands ###
