"""Set tennat as required

Revision ID: e7a8c6148f51
Revises: dd3da02417b1
Create Date: 2025-08-17 16:17:35.523218

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e7a8c6148f51"
down_revision = "dd3da02417b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fsuser",
        "user_tenant",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fsuser",
        "user_tenant",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=120),
        nullable=True,
    )
    # ### end Alembic commands ###
