"""Disconnect submission

Revision ID: e9bf944eff96
Revises: 3f711d7877ca
Create Date: 2025-08-25 09:52:28.827269

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e9bf944eff96"
down_revision = "3f711d7877ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_submission_enum_project_collaborator", "submission", type_="foreignkey"
    )
    op.drop_index("fk_submission_enumerator1_idx", table_name="submission")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_submission_enumerator1_idx",
        "submission",
        ["enum_project", "coll_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_submission_enum_project_collaborator",
        "submission",
        "collaborator",
        ["enum_project", "coll_id"],
        ["project_id", "coll_id"],
    )

    # ### end Alembic commands ###
