"""New controlling classes

Revision ID: eab2cc23d659
Revises: 01ddfd994185
Create Date: 2025-08-05 21:17:45.235569

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "eab2cc23d659"
down_revision = "01ddfd994185"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("tenant_id", sa.Unicode(length=120), nullable=False),
        sa.Column("tenant_name", sa.Unicode(length=120), nullable=True),
        sa.Column("tenant_cdate", sa.DateTime(), nullable=True),
        sa.Column(
            "extras", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
        sa.Column(
            "tags", mysql.MEDIUMTEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenant")),
    )
    op.create_table(
        "userworkspace",
        sa.Column("workspace_id", sa.Unicode(length=120), nullable=False),
        sa.Column("user_id", sa.Unicode(length=120), nullable=False),
        sa.Column("access_date", sa.DateTime(), nullable=True),
        sa.Column("access_type", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fsuser.user_id"],
            name=op.f("fk_userworkspace_user_id_fsuser"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["fsuser.user_id"],
            name=op.f("fk_userworkspace_workspace_id_fsuser"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "user_id", name=op.f("pk_userworkspace")
        ),
    )
    op.add_column(
        "fsuser",
        sa.Column(
            "user_is_workspace",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fsuser", "user_is_workspace")
    op.drop_table("userworkspace")
    op.drop_table("tenant")
    # ### end Alembic commands ###
