"""Remove emails from collaborators

Revision ID: f1387225be0e
Revises: 1f6d575c0d2a
Create Date: 2025-08-25 10:43:53.077397

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f1387225be0e"
down_revision = "1f6d575c0d2a"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE collaborator SET coll_email = null")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
