"""Add products and tasks

Revision ID: f41d23fed275
Revises: 0850741befc2
Create Date: 2019-03-03 09:37:21.575740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f41d23fed275"
down_revision = "0850741befc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finishedtask",
        sa.Column("task_id", sa.Unicode(length=64), nullable=False),
        sa.Column("task_enumber", sa.INTEGER(), nullable=True),
        sa.Column("task_error", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_finishedtask")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "task",
        sa.Column("task_id", sa.Unicode(length=64), nullable=False),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_task")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "product",
        sa.Column("celery_taskid", sa.Unicode(length=64), nullable=False),
        sa.Column("process_name", sa.Unicode(length=120), nullable=False),
        sa.Column("project_id", sa.Unicode(length=64), nullable=False),
        sa.Column("form_id", sa.Unicode(length=120), nullable=False),
        sa.Column("product_id", sa.Unicode(length=64), nullable=False),
        sa.Column("output_id", sa.Unicode(length=64), nullable=False),
        sa.Column("output_mimetype", sa.Unicode(length=120), nullable=False),
        sa.Column("datetime_added", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id", "form_id"],
            ["odkform.project_id", "odkform.form_id"],
            name=op.f("fk_product_project_id_odkform"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("celery_taskid", name=op.f("pk_product")),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("task")
    op.drop_table("finishedtask")
    # ### end Alembic commands ###
