"""Add FA fields to tenant

Revision ID: f8cfdffd5344
Revises: c45b3b09b281
Create Date: 2026-05-12 13:46:52.273541

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f8cfdffd5344"
down_revision = "c45b3b09b281"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant", sa.Column("fa_query_user", sa.Unicode(length=64), nullable=True)
    )
    op.add_column(
        "tenant", sa.Column("fa_query_password", sa.Unicode(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant", "fa_query_password")
    op.drop_column("tenant", "fa_query_user")
    # ### end Alembic commands ###
