"""Connect again the table of jsonhistory

Revision ID: fa70adf2eb40
Revises: 4d97d0eedaf3
Create Date: 2025-08-25 10:21:33.568005

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fa70adf2eb40"
down_revision = "4d97d0eedaf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "fk_jsonhistory_enumerator1_idx", "jsonhistory", ["coll_uuid"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_jsonhistory_coll_uuid_collaborator"),
        "jsonhistory",
        "collaborator",
        ["coll_uuid"],
        ["coll_uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_jsonhistory_coll_uuid_collaborator"), "jsonhistory", type_="foreignkey"
    )
    op.drop_index("fk_jsonhistory_enumerator1_idx", table_name="jsonhistory")
    # ### end Alembic commands ###
