"""Add form type

Revision ID: fc1b66b49bd4
Revises: d43afcb02554
Create Date: 2019-04-09 07:55:31.709198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1b66b49bd4'
down_revision = 'd43afcb02554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odkform', sa.Column('form_type', sa.INTEGER(), server_default=sa.text("'1'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odkform', 'form_type')
    # ### end Alembic commands ###
