-- Code generated by JXFormToMySQL
-- -j /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/b.srv -t maintable -v I_D -c /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/create.sql -C /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/create.xml -i /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/insert.sql -D /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/drop.sql -I /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/insert.xml -m /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/metadata.sql -f /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/manifest.xml -T /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/iso639.sql -e /home/cquiros/temp/formshare/odk/forms/447d0e11-baa8-46d9-a93f-c09307fd74c5/repository/temp -o m /home/cquiros/temp/formshare/odk/tmp/1d875376-0bbd-43d9-82cd-d5fed567962c/cantones.csv /home/cquiros/temp/formshare/odk/tmp/1d875376-0bbd-43d9-82cd-d5fed567962c/distritos.csv 
-- Created: Wed December 30 2020 9:45:31 am
-- by: JXFormToMySQL Version 1.0
-- WARNING! All changes made in this file might be lost when running JXFormToMySQL again

CREATE TABLE IF NOT EXISTS lkpplanted_units(
planted_units_cod varchar(2) NOT NULL COMMENT "Code", 
planted_units_des varchar(16) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (planted_units_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “planted_units”"; 
CREATE UNIQUE INDEX rowuuid1 ON lkpplanted_units(rowuuid);
delimiter $$

CREATE TRIGGER T0c203b26_83eb_4bb4_b2b5_9733b9575637 BEFORE INSERT ON lkpplanted_units FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpaves(
aves_cod varchar(7) NOT NULL COMMENT "Code", 
aves_des varchar(15) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (aves_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “aves”"; 
CREATE UNIQUE INDEX rowuuid2 ON lkpaves(rowuuid);
delimiter $$

CREATE TRIGGER T940b825c_03d3_461b_9d45_cd7ccc9a97ae BEFORE INSERT ON lkpaves FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkparea_units(
area_units_cod varchar(7) NOT NULL COMMENT "Code", 
area_units_des varchar(9) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (area_units_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “area_units”"; 
CREATE UNIQUE INDEX rowuuid3 ON lkparea_units(rowuuid);
delimiter $$

CREATE TRIGGER Td7394e8a_f68f_4577_8fed_706206810762 BEFORE INSERT ON lkparea_units FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpwho_family(
who_family_cod varchar(21) NOT NULL COMMENT "Code", 
who_family_des varchar(35) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (who_family_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “who_family”"; 
CREATE UNIQUE INDEX rowuuid4 ON lkpwho_family(rowuuid);
delimiter $$

CREATE TRIGGER T4edc7fee_0877_4307_a360_79b93cbbefb3 BEFORE INSERT ON lkpwho_family FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpagua(
agua_cod varchar(21) NOT NULL COMMENT "Code", 
agua_des varchar(19) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (agua_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “agua”"; 
CREATE UNIQUE INDEX rowuuid5 ON lkpagua(rowuuid);
delimiter $$

CREATE TRIGGER T436ec9cc_19fd_4600_b607_e10a60f200fd BEFORE INSERT ON lkpagua FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpagua_disp(
agua_disp_cod varchar(10) NOT NULL COMMENT "Code", 
agua_disp_des varchar(33) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (agua_disp_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “agua_disp”"; 
CREATE UNIQUE INDEX rowuuid6 ON lkpagua_disp(rowuuid);
delimiter $$

CREATE TRIGGER Tfe8817a7_3ea1_4b6b_8775_77e913ccddea BEFORE INSERT ON lkpagua_disp FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkplivestock_list(
livestock_list_cod varchar(14) NOT NULL COMMENT "Code", 
livestock_list_des varchar(25) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (livestock_list_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “livestock_list”"; 
CREATE UNIQUE INDEX rowuuid7 ON lkplivestock_list(rowuuid);
delimiter $$

CREATE TRIGGER T85f0f0f2_2ab3_462d_a368_abd35cae2e52 BEFORE INSERT ON lkplivestock_list FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpcrop_list(
crop_list_cod varchar(28) NOT NULL COMMENT "Code", 
crop_list_des varchar(28) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (crop_list_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “crop_list”"; 
CREATE UNIQUE INDEX rowuuid8 ON lkpcrop_list(rowuuid);
delimiter $$

CREATE TRIGGER T49af6b7b_bffe_4466_87ae_75cab070c840 BEFORE INSERT ON lkpcrop_list FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpganaderia(
ganaderia_cod varchar(7) NOT NULL COMMENT "Code", 
ganaderia_des varchar(28) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (ganaderia_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “ganaderia”"; 
CREATE UNIQUE INDEX rowuuid9 ON lkpganaderia(rowuuid);
delimiter $$

CREATE TRIGGER T76523565_c07d_4bed_86b6_987b499f857d BEFORE INSERT ON lkpganaderia FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpunidad_ensilaje(
unidad_ensilaje_cod varchar(9) NOT NULL COMMENT "Code", 
unidad_ensilaje_des varchar(16) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (unidad_ensilaje_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “unidad_ensilaje”"; 
CREATE UNIQUE INDEX rowuuid10 ON lkpunidad_ensilaje(rowuuid);
delimiter $$

CREATE TRIGGER T473641cf_17e8_4489_9c91_b746e526d5b6 BEFORE INSERT ON lkpunidad_ensilaje FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpland_tenure(
land_tenure_cod varchar(13) NOT NULL COMMENT "Code", 
land_tenure_des varchar(64) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (land_tenure_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “land_tenure”"; 
CREATE UNIQUE INDEX rowuuid11 ON lkpland_tenure(rowuuid);
delimiter $$

CREATE TRIGGER T0af8a2e8_1758_439b_9c6e_f171ebfb640b BEFORE INSERT ON lkpland_tenure FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpprovincia(
provincia_cod int(1) NOT NULL COMMENT "Code", 
provincia_des varchar(10) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (provincia_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “provincia”"; 
CREATE UNIQUE INDEX rowuuid12 ON lkpprovincia(rowuuid);
delimiter $$

CREATE TRIGGER Tcec3806b_4ecc_410b_b9df_ef3a4debe7bf BEFORE INSERT ON lkpprovincia FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpproporcion(
proporcion_cod varchar(16) NOT NULL COMMENT "Code", 
proporcion_des varchar(16) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (proporcion_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “proporcion”"; 
CREATE UNIQUE INDEX rowuuid13 ON lkpproporcion(rowuuid);
delimiter $$

CREATE TRIGGER Tf7ce000f_21ad_48d9_9582_ebb6332aa363 BEFORE INSERT ON lkpproporcion FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpyes_no(
yes_no_cod varchar(1) NOT NULL COMMENT "Code", 
yes_no_des varchar(2) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (yes_no_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “yes_no”"; 
CREATE UNIQUE INDEX rowuuid14 ON lkpyes_no(rowuuid);
delimiter $$

CREATE TRIGGER Tbb476479_25c0_482e_96d3_d458cda1d64a BEFORE INSERT ON lkpyes_no FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpcanton(
canton_cod int(2) NOT NULL COMMENT "Code", 
canton_des varchar(19) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (canton_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “canton”"; 
CREATE UNIQUE INDEX rowuuid15 ON lkpcanton(rowuuid);
delimiter $$

CREATE TRIGGER Tb1750548_4b7e_4565_a8e7_905220461370 BEFORE INSERT ON lkpcanton FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpwork_away(
work_away_cod varchar(16) NOT NULL COMMENT "Code", 
work_away_des varchar(30) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (work_away_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “work_away”"; 
CREATE UNIQUE INDEX rowuuid16 ON lkpwork_away(rowuuid);
delimiter $$

CREATE TRIGGER Tb3e1c493_07c0_4187_87c8_6b6a78cc90b5 BEFORE INSERT ON lkpwork_away FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpdistrito(
distrito_cod int(3) NOT NULL COMMENT "Code", 
distrito_des varchar(28) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (distrito_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “distrito”"; 
CREATE UNIQUE INDEX rowuuid17 ON lkpdistrito(rowuuid);
delimiter $$

CREATE TRIGGER T5b338b5d_d070_4f97_a661_7fb7d53ebcb3 BEFORE INSERT ON lkpdistrito FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkphouseholdtype(
householdtype_cod varchar(12) NOT NULL COMMENT "Code", 
householdtype_des varchar(45) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (householdtype_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “householdtype”"; 
CREATE UNIQUE INDEX rowuuid18 ON lkphouseholdtype(rowuuid);
delimiter $$

CREATE TRIGGER T9e146100_e80d_476b_ac7a_c8cd47fb1353 BEFORE INSERT ON lkphouseholdtype FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkpmale_female(
male_female_cod varchar(1) NOT NULL COMMENT "Code", 
male_female_des varchar(6) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (male_female_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “male_female”"; 
CREATE UNIQUE INDEX rowuuid19 ON lkpmale_female(rowuuid);
delimiter $$

CREATE TRIGGER T1bf29117_433a_4d9b_92d9_71acd90cdddb BEFORE INSERT ON lkpmale_female FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS lkphh_position(
hh_position_cod varchar(12) NOT NULL COMMENT "Code", 
hh_position_des varchar(39) COMMENT "Description", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (hh_position_cod ) )
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Lookup table for list name “hh_position”"; 
CREATE UNIQUE INDEX rowuuid20 ON lkphh_position(rowuuid);
delimiter $$

CREATE TRIGGER T083047ad_a3a6_4c75_9699_3b9cdc270cc8 BEFORE INSERT ON lkphh_position FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS maintable(
surveyid varchar(80) COMMENT "Submission ID", 
originid varchar(15) COMMENT "Origin", 
_submitted_by varchar(255) COMMENT "Submitted by", 
_xform_id_string varchar(255) COMMENT "XForm ID", 
_submitted_date datetime COMMENT "Submitted date", 
_geopoint varchar(80) COMMENT "GPS point", 
_longitude double COMMENT "GPS Point Longitude", 
_latitude double COMMENT "GPS Point Latitude", 
_elevation decimal(9,3) COMMENT "GPS Point Elevation", 
_precision decimal(9,3) COMMENT "GPS Point Precision", 
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
interviewername text COMMENT "Nombre del entrevistador", 
deviceid varchar(30) COMMENT "Without label", 
starttime_auto datetime COMMENT "Without label", 
starttime_calculated text COMMENT "Without label", 
participation varchar(1) COMMENT "¿Esta usted de acuerdo en proveer información para esta encuesta?", 
provincia int(1) COMMENT "Seleccione una provincia", 
canton int(2) COMMENT "Seleccione un canton", 
distrito int(3) COMMENT "Seleccione un distrito", 
caserio_nombre text COMMENT "Nombre del caserio direccion exacta", 
respondentname text COMMENT "¿Cuál es su nombre?", 
respondentsex varchar(1) COMMENT "¿El entrevistado es hombre o mujer?", 
respondent_is_head varchar(1) COMMENT "¿Es usted el/la jefe(a) de la familia?", 
household_position varchar(12) COMMENT "¿Cuál es su relacion con el/la jefe(a) del hogar?", 
household_type varchar(12) COMMENT "La persona jefe del hogar, ¿es casada o tiene pareja ?", 
casa_productor varchar(1) COMMENT "¿Vive el agricultor y su familia en la finca?", 
direccion_de_la_casa text COMMENT "Dirección de la casa:", 
numero_casa int(9) COMMENT "Teléfono de la casa:", 
numero_movil int(9) COMMENT "Teléfono móvil dueño finca:", 
work_away varchar(16) COMMENT "El jefe de la familia (o su pareja), ¿trabajan y viven lejos de su hogar?", 
children_under_4 int(9) COMMENT "¿Cuántos niños de tres años o menos viven en su hogar?", 
children_4to10 int(9) COMMENT "¿Cuántos niños entre los 4 y 10 años viven en su hogar?", 
children_4to10_educacion varchar(1) COMMENT "¿Todos los niños entre 6 y 13 años que viven en su hogar, asisten a la escuela en el presente ciclo escolar ?", 
males11to24 int(9) COMMENT "¿Cuántos varones entre 11 y 24 años viven en su hogar?", 
females11to24 int(9) COMMENT "¿Cuantas mujeres entre 11 y 24 años viven en su hogar?", 
males25to50 int(9) COMMENT "¿Cuántos hombres entre 25 y 50 años viven en su hogar?", 
females25to50 int(9) COMMENT "¿Cuántas mujeres entre 25 y 50 años viven en su hogar?", 
malesover50 int(9) COMMENT "¿Cuántos señores mayores de 50 años viven en su hogar?", 
femalesover50 int(9) COMMENT "¿Cuántas señoras mayores de 50 años viven en su hogar?", 
adultsover65 int(9) COMMENT "¿Cuántos personas mayores de 65 años viven en su hogar?", 
adultsover65_pension varchar(1) COMMENT "¿Alguna persona mayor de 65 años, recibe pensión de la C.C.S.S.?", 
land_tenure varchar(49) COMMENT "¿La finca es propia, alquilada o prestada?", 
landowned decimal(17,3) COMMENT "¿Cuánta area tiene su finca?", 
unitland_owned varchar(7) COMMENT "Unidades de área:", 
land_ownership varchar(91) COMMENT "¿Quien es el dueño de las tierras?", 
landrentin decimal(17,3) COMMENT "¿Qué superficie renta para trabajar?", 
unitland_rentin varchar(7) COMMENT "Unidades de área:", 
landrentout decimal(17,3) COMMENT "¿Qué superficie renta de sus tierras a otras personas ?", 
unitland_rentout varchar(7) COMMENT "Unidades de área:", 
landcultivated decimal(17,3) COMMENT "¿Cuánto suma el área de todos los terrenos que utiliza para cultivar ?", 
unitland varchar(7) COMMENT "Unidades de área:", 
areaunits_other text COMMENT "Especifique las unidades si son distintas:", 
agua_finca varchar(21) COMMENT "Como suple el agua a su finca?", 
agua_disponible varchar(10) COMMENT "Tiempo de disponibilidad de la fuente de agua", 
grow_crops varchar(1) COMMENT "¿Usted siembra algún cultivo?", 
crops varchar(671) COMMENT "¿ACTUALMENTE, cuáles son los CUATRO cultivos más importantes que tiene en su finca?", 
crop_count text COMMENT "Without label", 
crops_other1 text COMMENT "Especifíque otro cultivo No. 1", 
crops_other2 text COMMENT "Especifíque otro cultivo No. 2", 
crops_other3 text COMMENT "Especifíque otro cultivo No. 3", 
livestock_owners varchar(1) COMMENT "¿Tiene ganado u otros animales?", 
livestock varchar(98) COMMENT "¿Cuáles animales tienen en su finca?", 
livestock_count text COMMENT "Without label", 
tiene_ensilaje varchar(1) COMMENT "Tiene ensilaje?", 
ensilaje decimal(17,3) COMMENT "Cantidad ensilada", 
ensilaje_unit varchar(9) COMMENT "Unidad", 
offfarm_incomes_any varchar(1) COMMENT "¿Tiene algúna fuente de ingresos aparte de lo que obtiene de la venta de los productos de la finca?", 
offfarm_income_ag varchar(16) COMMENT "¿Qué tanto de esos ingresos son relacionados a agricultura? E.g., Jornalero agricola", 
prop_onfarm varchar(16) COMMENT "Del ingreso total cuanto proviene de la finca", 
prop_crops varchar(16) COMMENT "Del ingreso total de la finca cuanto proviene cultivos", 
gps varchar(80) COMMENT "Coordenadas GPS de la Finca", 
endtime_auto datetime COMMENT "Without label", 
endtime_calculated text COMMENT "Without label", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d ) , 
INDEX fk_0fed853c_38a2_4ad5_a13a_1a0d6e895b30 (participation) , 
INDEX fk_0297485e_9aa2_4d0a_ba21_66768c9a59a3 (provincia) , 
INDEX fk_949145fa_c30b_40f3_8468_48116e9e7c54 (canton) , 
INDEX fk_9ee8aee5_8a74_4987_8ae6_8a4b97bbf97b (distrito) , 
INDEX fk_081c1303_25f6_4084_a555_7b62cc6d3ece (respondentsex) , 
INDEX fk_64aaaae1_2532_4367_b699_20a8defc94f1 (respondent_is_head) , 
INDEX fk_016c21d7_1a11_459b_83f1_6c0d61bfc906 (household_position) , 
INDEX fk_5089dd30_f5ec_4278_a63d_c4528c86db5e (household_type) , 
INDEX fk_916fb03d_b607_4684_aaf1_8a41aae2bc33 (casa_productor) , 
INDEX fk_5984122a_246f_4843_9441_bd3de9201e2b (work_away) , 
INDEX fk_e78f8d52_7e94_48de_8a16_f2455b59ffd6 (children_4to10_educacion) , 
INDEX fk_cd9fd432_69d2_4861_82d2_12649b97cf0b (adultsover65_pension) , 
INDEX fk_33a2b392_90a1_49ec_b019_f7b6da9ccb5b (unitland_owned) , 
INDEX fk_e81717a5_9ad6_49ca_8433_1f3d1950d5b9 (unitland_rentin) , 
INDEX fk_9a7e4cca_b997_4961_a6ca_d5c5dc1b6cfe (unitland_rentout) , 
INDEX fk_2ba3aa96_188a_4d33_a26d_519c41149397 (unitland) , 
INDEX fk_0e9008e3_6a9a_48cf_b4a0_587108966b21 (agua_finca) , 
INDEX fk_6cfe3ee6_bfe2_46fb_9497_fbead17f296c (agua_disponible) , 
INDEX fk_b26fad86_a937_4c6d_b98a_dba629f67484 (grow_crops) , 
INDEX fk_60511fb9_4fc6_4bf3_9507_e23de951a134 (livestock_owners) , 
INDEX fk_705460e8_cd66_4f17_b492_25af027c19e5 (tiene_ensilaje) , 
INDEX fk_1d48a9d8_d26d_42e6_b84c_cb8afc7609a3 (ensilaje_unit) , 
INDEX fk_64db155f_1b60_4af8_9b00_73fceedbc72d (offfarm_incomes_any) , 
INDEX fk_fc5e043b_4025_4b39_9323_7e0551127ddf (offfarm_income_ag) , 
INDEX fk_8ab4565f_059c_483c_980b_b878003f1c7d (prop_onfarm) , 
INDEX fk_4a23c8a3_51e3_420e_a970_b3e4452a5622 (prop_crops) , 
CONSTRAINT fk_0fed853c_38a2_4ad5_a13a_1a0d6e895b30
FOREIGN KEY (participation)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_0297485e_9aa2_4d0a_ba21_66768c9a59a3
FOREIGN KEY (provincia)
REFERENCES lkpprovincia (provincia_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_949145fa_c30b_40f3_8468_48116e9e7c54
FOREIGN KEY (canton)
REFERENCES lkpcanton (canton_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_9ee8aee5_8a74_4987_8ae6_8a4b97bbf97b
FOREIGN KEY (distrito)
REFERENCES lkpdistrito (distrito_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_081c1303_25f6_4084_a555_7b62cc6d3ece
FOREIGN KEY (respondentsex)
REFERENCES lkpmale_female (male_female_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_64aaaae1_2532_4367_b699_20a8defc94f1
FOREIGN KEY (respondent_is_head)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_016c21d7_1a11_459b_83f1_6c0d61bfc906
FOREIGN KEY (household_position)
REFERENCES lkphh_position (hh_position_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_5089dd30_f5ec_4278_a63d_c4528c86db5e
FOREIGN KEY (household_type)
REFERENCES lkphouseholdtype (householdtype_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_916fb03d_b607_4684_aaf1_8a41aae2bc33
FOREIGN KEY (casa_productor)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_5984122a_246f_4843_9441_bd3de9201e2b
FOREIGN KEY (work_away)
REFERENCES lkpwork_away (work_away_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_e78f8d52_7e94_48de_8a16_f2455b59ffd6
FOREIGN KEY (children_4to10_educacion)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_cd9fd432_69d2_4861_82d2_12649b97cf0b
FOREIGN KEY (adultsover65_pension)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_33a2b392_90a1_49ec_b019_f7b6da9ccb5b
FOREIGN KEY (unitland_owned)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_e81717a5_9ad6_49ca_8433_1f3d1950d5b9
FOREIGN KEY (unitland_rentin)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_9a7e4cca_b997_4961_a6ca_d5c5dc1b6cfe
FOREIGN KEY (unitland_rentout)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_2ba3aa96_188a_4d33_a26d_519c41149397
FOREIGN KEY (unitland)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_0e9008e3_6a9a_48cf_b4a0_587108966b21
FOREIGN KEY (agua_finca)
REFERENCES lkpagua (agua_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_6cfe3ee6_bfe2_46fb_9497_fbead17f296c
FOREIGN KEY (agua_disponible)
REFERENCES lkpagua_disp (agua_disp_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_b26fad86_a937_4c6d_b98a_dba629f67484
FOREIGN KEY (grow_crops)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_60511fb9_4fc6_4bf3_9507_e23de951a134
FOREIGN KEY (livestock_owners)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_705460e8_cd66_4f17_b492_25af027c19e5
FOREIGN KEY (tiene_ensilaje)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_1d48a9d8_d26d_42e6_b84c_cb8afc7609a3
FOREIGN KEY (ensilaje_unit)
REFERENCES lkpunidad_ensilaje (unidad_ensilaje_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_64db155f_1b60_4af8_9b00_73fceedbc72d
FOREIGN KEY (offfarm_incomes_any)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_fc5e043b_4025_4b39_9323_7e0551127ddf
FOREIGN KEY (offfarm_income_ag)
REFERENCES lkpproporcion (proporcion_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_8ab4565f_059c_483c_980b_b878003f1c7d
FOREIGN KEY (prop_onfarm)
REFERENCES lkpproporcion (proporcion_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_4a23c8a3_51e3_420e_a970_b3e4452a5622
FOREIGN KEY (prop_crops)
REFERENCES lkpproporcion (proporcion_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Main table - Set a description"; 
CREATE UNIQUE INDEX rowuuid47 ON maintable(rowuuid);
delimiter $$

CREATE TRIGGER T8e4554a6_93f3_4f27_a485_1026ca33cd04 BEFORE INSERT ON maintable FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS maintable_msel_land_tenure(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
land_tenure varchar(13) NOT NULL COMMENT "¿La finca es propia, alquilada o prestada?", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , land_tenure ) , 
INDEX fk_2d0b06a3_6f26_4478_b0e5_93fa84f17eb5 (land_tenure) , 
INDEX fk49_maintable_msel_land_tenure_maintable (i_d) , 
CONSTRAINT fk_2d0b06a3_6f26_4478_b0e5_93fa84f17eb5
FOREIGN KEY (land_tenure)
REFERENCES lkpland_tenure (land_tenure_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk49_maintable_msel_land_tenure_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Table for multiple select of field land_tenure in table maintable"; 
CREATE UNIQUE INDEX rowuuid50 ON maintable_msel_land_tenure(rowuuid);
delimiter $$

CREATE TRIGGER T105de6b4_d9d0_4c46_a72d_8fa6a3975be9 BEFORE INSERT ON maintable_msel_land_tenure FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS maintable_msel_land_ownership(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
land_ownership varchar(21) NOT NULL COMMENT "¿Quien es el dueño de las tierras?", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , land_ownership ) , 
INDEX fk_b8a36533_0e4d_4664_aadc_363ee0600de5 (land_ownership) , 
INDEX fk52_maintable_msel_land_ownership_maintable (i_d) , 
CONSTRAINT fk_b8a36533_0e4d_4664_aadc_363ee0600de5
FOREIGN KEY (land_ownership)
REFERENCES lkpwho_family (who_family_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk52_maintable_msel_land_ownership_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Table for multiple select of field land_ownership in table maintable"; 
CREATE UNIQUE INDEX rowuuid53 ON maintable_msel_land_ownership(rowuuid);
delimiter $$

CREATE TRIGGER T0cee726f_82f4_447f_8730_8be23b2034a7 BEFORE INSERT ON maintable_msel_land_ownership FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS maintable_msel_crops(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
crops varchar(28) NOT NULL COMMENT "¿ACTUALMENTE, cuáles son los CUATRO cultivos más importantes que tiene en su finca?", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , crops ) , 
INDEX fk_d487d078_ee89_454b_9d43_836cae9e4e07 (crops) , 
INDEX fk55_maintable_msel_crops_maintable (i_d) , 
CONSTRAINT fk_d487d078_ee89_454b_9d43_836cae9e4e07
FOREIGN KEY (crops)
REFERENCES lkpcrop_list (crop_list_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk55_maintable_msel_crops_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Table for multiple select of field crops in table maintable"; 
CREATE UNIQUE INDEX rowuuid56 ON maintable_msel_crops(rowuuid);
delimiter $$

CREATE TRIGGER T621607f5_ae94_41fd_a689_24b2d6eaab37 BEFORE INSERT ON maintable_msel_crops FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS crop_repeat(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
crop_repeat_rowid int(3) NOT NULL COMMENT "Unique Row ID", 
crop_rep_number text COMMENT "Without label", 
crop_name varchar(28) COMMENT "Le preguntaré sobre cada uno de los cultivos más importantes. Defina al cultivo número ${crop_rep_number}:", 
crop_label text COMMENT "Without label", 
crop_planted decimal(17,3) COMMENT "¿Canta area tiene sembrado del cultivo ${crop_label} ?", 
crop_yield_units varchar(2) COMMENT "unidades:", 
crop_irrigated varchar(1) COMMENT "¿Tiene este cultivo bajo riego?", 
fecha_siembra date COMMENT "Cuando sembro el cultivo", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , crop_repeat_rowid ) , 
INDEX fk_166831df_cec0_4b4d_8b13_45a70a50902d (crop_name) , 
INDEX fk_60f8f119_0e52_4bd0_9bc5_1f6b61e9ee5c (crop_yield_units) , 
INDEX fk_887174d3_add7_4d48_b415_b2da5b94fb14 (crop_irrigated) , 
INDEX fk60_crop_repeat_maintable (i_d) , 
CONSTRAINT fk_166831df_cec0_4b4d_8b13_45a70a50902d
FOREIGN KEY (crop_name)
REFERENCES lkpcrop_list (crop_list_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_60f8f119_0e52_4bd0_9bc5_1f6b61e9ee5c
FOREIGN KEY (crop_yield_units)
REFERENCES lkpplanted_units (planted_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_887174d3_add7_4d48_b415_b2da5b94fb14
FOREIGN KEY (crop_irrigated)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk60_crop_repeat_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Detalles sobre cada cultivo (Loop)"; 
CREATE UNIQUE INDEX rowuuid61 ON crop_repeat(rowuuid);
delimiter $$

CREATE TRIGGER T5cdea0bb_6572_49cc_9674_f649fd82c63f BEFORE INSERT ON crop_repeat FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS maintable_msel_livestock(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
livestock varchar(14) NOT NULL COMMENT "¿Cuáles animales tienen en su finca?", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , livestock ) , 
INDEX fk_80f3edb5_dfe7_4bef_8e10_87a08f7237df (livestock) , 
INDEX fk63_maintable_msel_livestock_maintable (i_d) , 
CONSTRAINT fk_80f3edb5_dfe7_4bef_8e10_87a08f7237df
FOREIGN KEY (livestock)
REFERENCES lkplivestock_list (livestock_list_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk63_maintable_msel_livestock_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Table for multiple select of field livestock in table maintable"; 
CREATE UNIQUE INDEX rowuuid64 ON maintable_msel_livestock(rowuuid);
delimiter $$

CREATE TRIGGER T3397b325_4ad1_459c_964d_b711771839fe BEFORE INSERT ON maintable_msel_livestock FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

CREATE TABLE IF NOT EXISTS livestock_repeat(
i_d varchar(255) NOT NULL COMMENT "Cuál es su N° de cédula?", 
livestock_repeat_rowid int(3) NOT NULL COMMENT "Unique Row ID", 
live_rep_number text COMMENT "Without label", 
live_name varchar(14) COMMENT "Le preguntaré sobre cada uno de los animales más importantes. Defina al animal número ${live_rep_number}:", 
live_label text COMMENT "Without label", 
live_number int(9) COMMENT "¿Cantos animales tiene de ${live_label} ?", 
bee_number int(9) COMMENT "Cuantas colmenas tiene", 
tipo_ganaderia varchar(7) COMMENT "Que tipo de ganadería tiene?", 
tipo_aves varchar(7) COMMENT "Que tipo de avicultura tiene?", 
tiene_pastos varchar(1) COMMENT "Tiene pastos", 
pasto_total decimal(17,3) COMMENT "Área de pastos total", 
pasto_total_unit varchar(7) COMMENT "Unidad del area", 
pasto_piso decimal(17,3) COMMENT "Área de pastos de piso naturalizado", 
pasto_piso_unit varchar(7) COMMENT "Unidad del area", 
pasto_mejorado decimal(17,3) COMMENT "Área de pastos de piso mejorado", 
pasto_mejorado_unit varchar(7) COMMENT "Unidad del area", 
pasto_corte decimal(17,3) COMMENT "Área de pastos de corte", 
pasto_corte_unit varchar(7) COMMENT "Unidad del area", 
ensilaje decimal(17,3) COMMENT "Área de pastos de ensilaje o henificación", 
ensilaje_unit varchar(7) COMMENT "Unidad del area", 
fecha_pasto date COMMENT "Fecha de siembra del pasto de ensilaje o henificación", 
rowuuid varchar(80) COMMENT "Unique Row Identifier (UUID)", 
PRIMARY KEY (i_d , livestock_repeat_rowid ) , 
INDEX fk_3197a7b4_731b_4fa0_8490_211be86f444d (live_name) , 
INDEX fk_cc33b370_fcf8_471e_bd96_1b7970e3abdf (tipo_ganaderia) , 
INDEX fk_b40264ad_5bce_4fe5_93f3_f9ba765a63a7 (tipo_aves) , 
INDEX fk_e8c0c819_cba6_4575_b9a6_3229731da836 (tiene_pastos) , 
INDEX fk_bc391344_dd8b_4527_b2ad_3813f710c171 (pasto_total_unit) , 
INDEX fk_75e46ac4_5f84_42bc_af5e_ff563f72d962 (pasto_piso_unit) , 
INDEX fk_520c9954_b9d7_42dc_86bb_2d129acb4b74 (pasto_mejorado_unit) , 
INDEX fk_63cb155a_48f8_493d_a8b5_36fc1bf3b646 (pasto_corte_unit) , 
INDEX fk_f2d6b9bc_6555_4c75_b06d_ca649c4a74df (ensilaje_unit) , 
INDEX fk74_livestock_repeat_maintable (i_d) , 
CONSTRAINT fk_3197a7b4_731b_4fa0_8490_211be86f444d
FOREIGN KEY (live_name)
REFERENCES lkplivestock_list (livestock_list_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_cc33b370_fcf8_471e_bd96_1b7970e3abdf
FOREIGN KEY (tipo_ganaderia)
REFERENCES lkpganaderia (ganaderia_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_b40264ad_5bce_4fe5_93f3_f9ba765a63a7
FOREIGN KEY (tipo_aves)
REFERENCES lkpaves (aves_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_e8c0c819_cba6_4575_b9a6_3229731da836
FOREIGN KEY (tiene_pastos)
REFERENCES lkpyes_no (yes_no_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_bc391344_dd8b_4527_b2ad_3813f710c171
FOREIGN KEY (pasto_total_unit)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_75e46ac4_5f84_42bc_af5e_ff563f72d962
FOREIGN KEY (pasto_piso_unit)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_520c9954_b9d7_42dc_86bb_2d129acb4b74
FOREIGN KEY (pasto_mejorado_unit)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_63cb155a_48f8_493d_a8b5_36fc1bf3b646
FOREIGN KEY (pasto_corte_unit)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk_f2d6b9bc_6555_4c75_b06d_ca649c4a74df
FOREIGN KEY (ensilaje_unit)
REFERENCES lkparea_units (area_units_cod)
ON DELETE RESTRICT 
ON UPDATE NO ACTION,
CONSTRAINT fk74_livestock_repeat_maintable
FOREIGN KEY (i_d)
REFERENCES maintable (i_d)
ON DELETE CASCADE 
ON UPDATE NO ACTION)
 ENGINE = InnoDB CHARSET=utf8 COMMENT = "Detalles sobre cada animal (Loop)"; 
CREATE UNIQUE INDEX rowuuid75 ON livestock_repeat(rowuuid);
delimiter $$

CREATE TRIGGER T895c458b_ea05_4c1e_b39f_3819af4a2507 BEFORE INSERT ON livestock_repeat FOR EACH ROW BEGIN IF (new.rowuuid IS NULL) THEN SET new.rowuuid = uuid(); ELSE IF (new.rowuuid NOT REGEXP '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}') THEN SET new.rowuuid = uuid(); END IF; END IF; END;$$
delimiter ;

