-- MySQL Script generated by MySQL Workbench
-- dom 22 jul 2018 12:24:39 EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema formshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formshare` DEFAULT CHARACTER SET latin1 ;
USE `formshare` ;

-- -----------------------------------------------------
-- Table `formshare`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `formshare`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`user` (
  `user_id` VARCHAR(120) NOT NULL,
  `user_name` VARCHAR(120) NULL DEFAULT NULL,
  `user_password` VARCHAR(120) NULL DEFAULT NULL,
  `user_about` TEXT NULL DEFAULT NULL,
  `user_cdate` DATETIME NULL DEFAULT NULL,
  `user_llogin` DATETIME NULL DEFAULT NULL,
  `user_super` INT(11) NULL DEFAULT '0',
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  `user_active` INT(11) NULL DEFAULT '1',
  `user_apikey` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`project` (
  `project_id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(120) NOT NULL,
  `project_name` TEXT NULL DEFAULT NULL,
  `project_abstract` TEXT NULL DEFAULT NULL,
  `project_cdate` VARCHAR(45) NULL DEFAULT NULL,
  `project_creator` VARCHAR(45) NULL DEFAULT NULL,
  `project_cremail` VARCHAR(45) NULL DEFAULT NULL,
  `project_contact` VARCHAR(120) NULL DEFAULT NULL,
  `project_coemail` VARCHAR(45) NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_user_id_user` (`user_id` ASC),
  CONSTRAINT `fk_project_user_id_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `formshare`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collaborator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collaborator` (
  `project_id` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  `coll_name` VARCHAR(120) NULL DEFAULT NULL,
  `coll_password` VARCHAR(120) NULL DEFAULT NULL,
  `coll_active` INT(11) NULL DEFAULT NULL,
  `coll_cdate` DATETIME NULL DEFAULT NULL,
  `coll_email` TEXT NULL DEFAULT NULL,
  `coll_telephone` VARCHAR(120) NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  `samas_project` VARCHAR(64) NULL,
  `sameas_coll` VARCHAR(120) NULL,
  PRIMARY KEY (`project_id`, `coll_id`),
  INDEX `fk_enumerator_enumerator1_idx` (`samas_project` ASC, `sameas_coll` ASC),
  CONSTRAINT `fk_enumerator_project_id_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `formshare`.`project` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_enumerator_enumerator1`
    FOREIGN KEY (`samas_project` , `sameas_coll`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collgroup` (
  `project_id` VARCHAR(64) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `group_desc` TEXT NULL DEFAULT NULL,
  `group_cdate` DATETIME NULL DEFAULT NULL,
  `group_active` INT(11) NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `group_id`),
  CONSTRAINT `fk_enumgroup_project_id_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `formshare`.`project` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collingroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collingroup` (
  `project_id` VARCHAR(64) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `enum_project` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  `coll_privileges` INT(11) NULL DEFAULT NULL,
  `join_date` DATETIME NULL,
  PRIMARY KEY (`project_id`, `group_id`, `enum_project`, `coll_id`),
  INDEX `fk_enumingroup_enumerator1` (`enum_project` ASC, `coll_id` ASC),
  INDEX `fk_enumingroup_enumerator1_idx` (`enum_project` ASC, `coll_id` ASC),
  CONSTRAINT `fk_enumingroup_enum_project_enumerator`
    FOREIGN KEY (`enum_project` , `coll_id`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_enumingroup_project_id_enumgroup`
    FOREIGN KEY (`project_id` , `group_id`)
    REFERENCES `formshare`.`collgroup` (`project_id` , `group_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`form` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `form_name` VARCHAR(120) NULL DEFAULT NULL,
  `form_cdate` DATETIME NULL DEFAULT NULL,
  `form_directory` VARCHAR(120) NULL DEFAULT NULL,
  `form_schema` VARCHAR(13) NULL DEFAULT NULL,
  `form_accsub` INT(11) NULL DEFAULT NULL,
  `form_testing` INT(11) NULL DEFAULT '0',
  `form_incversion` INT(11) NULL DEFAULT '0',
  `parent_project` VARCHAR(64) NULL DEFAULT NULL,
  `parent_form` VARCHAR(120) NULL DEFAULT NULL,
  `form_stage` INT(11) NULL DEFAULT NULL,
  `form_pkey` VARCHAR(120) NULL DEFAULT NULL,
  `form_deflang` VARCHAR(120) NULL DEFAULT NULL,
  `form_yesno` VARCHAR(120) NULL DEFAULT NULL,
  `form_othlangs` TEXT NULL DEFAULT NULL,
  `form_sepfile` TEXT NULL DEFAULT NULL,
  `form_xlsfile` TEXT NULL DEFAULT NULL,
  `form_xmlfile` TEXT NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `form_id`),
  INDEX `fk_form_form1_idx` (`parent_project` ASC, `parent_form` ASC),
  CONSTRAINT `fk_form_parent_project_form`
    FOREIGN KEY (`parent_project` , `parent_form`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`),
  CONSTRAINT `fk_form_project_id_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `formshare`.`project` (`project_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`formgrpaccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`formgrpaccess` (
  `project_id` VARCHAR(64) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `form_project` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `access_date` DATETIME NULL,
  PRIMARY KEY (`project_id`, `group_id`, `form_project`, `form_id`),
  INDEX `fk_grpsubmitter_form1` (`form_project` ASC, `form_id` ASC),
  INDEX `fk_grpsubmitter_form1_idx` (`form_project` ASC, `form_id` ASC),
  CONSTRAINT `fk_grpsubmitter_form_project_form`
    FOREIGN KEY (`form_project` , `form_id`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_grpsubmitter_project_id_enumgroup`
    FOREIGN KEY (`project_id` , `group_id`)
    REFERENCES `formshare`.`collgroup` (`project_id` , `group_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`jsonlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`jsonlog` (
  `form_id` VARCHAR(120) NOT NULL,
  `project_id` VARCHAR(64) NOT NULL,
  `log_id` VARCHAR(64) NOT NULL,
  `log_dtime` DATETIME NULL DEFAULT NULL,
  `json_file` TEXT NULL DEFAULT NULL,
  `log_file` TEXT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `enum_project` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`form_id`, `project_id`, `log_id`),
  INDEX `fk_jsonlog_enumerator1_idx` (`enum_project` ASC, `coll_id` ASC),
  INDEX `fk_jsonlog_form1_idx` (`project_id` ASC, `form_id` ASC),
  CONSTRAINT `fk_jsonlog_enum_project_enumerator`
    FOREIGN KEY (`enum_project` , `coll_id`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`),
  CONSTRAINT `fk_jsonlog_project_id_form`
    FOREIGN KEY (`project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`jsonhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`jsonhistory` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `log_id` VARCHAR(64) NOT NULL,
  `log_sequence` VARCHAR(12) NOT NULL,
  `log_dtime` DATETIME NULL DEFAULT NULL,
  `log_action` INT(11) NULL DEFAULT NULL,
  `log_commit` VARCHAR(12) NULL DEFAULT NULL,
  `log_notes` TEXT NULL DEFAULT NULL,
  `enum_project` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`project_id`, `form_id`, `log_id`, `log_sequence`),
  INDEX `fk_jsonhistory_enumerator1_idx` (`enum_project` ASC, `coll_id` ASC),
  INDEX `fk_jsonhistory_jsonlog1_idx` (`form_id` ASC, `project_id` ASC, `log_id` ASC),
  CONSTRAINT `fk_jsonhistory_enum_project_enumerator`
    FOREIGN KEY (`enum_project` , `coll_id`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`),
  CONSTRAINT `fk_jsonhistory_form_id_jsonlog`
    FOREIGN KEY (`form_id` , `project_id` , `log_id`)
    REFERENCES `formshare`.`jsonlog` (`form_id` , `project_id` , `log_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`septable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`septable` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `table_desc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `form_id`, `table_name`),
  CONSTRAINT `fk_septable_project_id_form`
    FOREIGN KEY (`project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`sepsection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`sepsection` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `section_id` VARCHAR(12) NOT NULL,
  `section_name` VARCHAR(120) NULL DEFAULT NULL,
  `section_desc` TEXT NULL DEFAULT NULL,
  `section_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `form_id`, `table_name`, `section_id`),
  CONSTRAINT `fk_sepsection_project_id_septable`
    FOREIGN KEY (`project_id` , `form_id` , `table_name`)
    REFERENCES `formshare`.`septable` (`project_id` , `form_id` , `table_name`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`sepitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`sepitems` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `item_name` VARCHAR(120) NOT NULL,
  `item_desc` TEXT NULL DEFAULT NULL,
  `item_xmlcode` TEXT NULL DEFAULT NULL,
  `item_notdisplay` INT(11) NULL DEFAULT NULL,
  `item_order` INT(11) NULL DEFAULT NULL,
  `section_project` VARCHAR(64) NOT NULL,
  `section_form` VARCHAR(120) NOT NULL,
  `section_table` VARCHAR(120) NOT NULL,
  `section_id` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`project_id`, `form_id`, `table_name`, `item_name`),
  INDEX `fk_sepitems_sepsection1_idx` (`section_project` ASC, `section_form` ASC, `section_table` ASC, `section_id` ASC),
  CONSTRAINT `fk_sepitems_project_id_septable`
    FOREIGN KEY (`project_id` , `form_id` , `table_name`)
    REFERENCES `formshare`.`septable` (`project_id` , `form_id` , `table_name`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_sepitems_section_project_sepsection`
    FOREIGN KEY (`section_project` , `section_form` , `section_table` , `section_id`)
    REFERENCES `formshare`.`sepsection` (`project_id` , `form_id` , `table_name` , `section_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`submission` (
  `project_id` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `submission_id` VARCHAR(64) NOT NULL,
  `submission_dtime` DATETIME NULL DEFAULT NULL,
  `submission_status` INT(11) NULL DEFAULT NULL,
  `enum_project` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  `md5sum` VARCHAR(120) NULL DEFAULT NULL,
  `sameas` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `form_id`, `submission_id`),
  INDEX `fk_submission_enumerator1_idx` (`enum_project` ASC, `coll_id` ASC),
  INDEX `fk_submission_form1_idx` (`project_id` ASC, `form_id` ASC),
  CONSTRAINT `fk_submission_enum_project_enumerator`
    FOREIGN KEY (`enum_project` , `coll_id`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_submission_project_id_form`
    FOREIGN KEY (`project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`formaccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`formaccess` (
  `project_id` VARCHAR(64) NOT NULL,
  `coll_id` VARCHAR(120) NOT NULL,
  `form_project` VARCHAR(64) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `coll_privileges` INT(11) NULL DEFAULT NULL,
  `access_date` DATETIME NULL,
  PRIMARY KEY (`project_id`, `coll_id`, `form_project`, `form_id`),
  INDEX `fk_submitter_form1` (`form_project` ASC, `form_id` ASC),
  INDEX `fk_submitter_form1_idx` (`form_project` ASC, `form_id` ASC),
  CONSTRAINT `fk_submitter_form_project_form`
    FOREIGN KEY (`form_project` , `form_id`)
    REFERENCES `formshare`.`form` (`project_id` , `form_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_submitter_project_id_enumerator`
    FOREIGN KEY (`project_id` , `coll_id`)
    REFERENCES `formshare`.`collaborator` (`project_id` , `coll_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`userlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`userlog` (
  `log_entry` VARCHAR(64) NOT NULL,
  `log_datetime` DATETIME NULL DEFAULT NULL,
  `access_type` INT(11) NULL DEFAULT NULL,
  `tableid` VARCHAR(45) NULL DEFAULT NULL,
  `action` TINYINT NULL DEFAULT NULL,
  `userid` VARCHAR(255) NULL DEFAULT NULL,
  `org` VARCHAR(32) NULL DEFAULT NULL,
  `project` VARCHAR(32) NULL DEFAULT NULL,
  `form` VARCHAR(120) NULL DEFAULT NULL,
  `collaborator` VARCHAR(32) NULL DEFAULT NULL,
  `groupid` VARCHAR(12) NULL DEFAULT NULL,
  `septable` VARCHAR(120) NULL DEFAULT NULL,
  `sepsection` VARCHAR(12) NULL DEFAULT NULL,
  `sepitem` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`log_entry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collaboratorlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collaboratorlog` (
  `log_entry` VARCHAR(64) NOT NULL,
  `log_datetime` DATETIME NULL DEFAULT NULL,
  `access_type` INT(11) NULL DEFAULT NULL,
  `interface` TINYINT NULL DEFAULT NULL,
  `action` INT(3) NULL DEFAULT NULL,
  `userid` VARCHAR(255) NULL DEFAULT NULL,
  `org` VARCHAR(32) NULL DEFAULT NULL,
  `project` VARCHAR(32) NULL DEFAULT NULL,
  `form` VARCHAR(120) NULL DEFAULT NULL,
  `collaborator` VARCHAR(32) NULL DEFAULT NULL,
  `logid` VARCHAR(64) NULL DEFAULT NULL,
  `commitid` VARCHAR(12) NULL DEFAULT NULL,
  `schemaid` VARCHAR(13) NULL DEFAULT NULL,
  `tableid` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`log_entry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
