-- MySQL Script generated by MySQL Workbench
-- Wed 27 Jun 2018 01:35:59 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema formshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formshare` DEFAULT CHARACTER SET utf8 ;
USE `formshare` ;

-- -----------------------------------------------------
-- Table `formshare`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`user` (
  `user_email` VARCHAR(255) NOT NULL,
  `user_fname` VARCHAR(120) NULL,
  `user_lname` VARCHAR(120) NULL,
  `user_password` VARCHAR(120) NULL,
  `user_about` TEXT NULL,
  `user_cdate` DATETIME NULL,
  `user_llogin` DATETIME NULL,
  `user_active` TINYINT NULL,
  `user_apikey` VARCHAR(64) NULL,
  `user_admin` TINYINT NULL,
  `tags` TEXT NULL,
  `extra` TEXT NULL,
  PRIMARY KEY (`user_email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`org`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`org` (
  `org_id` VARCHAR(32) NOT NULL,
  `org_name` VARCHAR(120) NULL,
  `org_address` VARCHAR(45) NULL,
  `org_logo` TEXT NULL,
  `org_active` TINYINT NULL,
  `tags` TEXT NULL,
  `extras` TEXT NULL,
  PRIMARY KEY (`org_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`userorg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`userorg` (
  `org_id` VARCHAR(32) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_admin` TINYINT NULL,
  `user_joined` DATETIME NULL,
  `extra` TEXT NULL,
  PRIMARY KEY (`org_id`, `user_email`),
  INDEX `fk_userorg_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_userorg_org`
    FOREIGN KEY (`org_id`)
    REFERENCES `formshare`.`org` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userorg_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `formshare`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`project` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `project_name` TEXT NULL DEFAULT NULL,
  `project_abstract` TEXT NULL DEFAULT NULL,
  `project_cdate` VARCHAR(45) NULL DEFAULT NULL,
  `project_creator` VARCHAR(45) NULL DEFAULT NULL,
  `project_cremail` VARCHAR(45) NULL DEFAULT NULL,
  `project_contact` VARCHAR(120) NULL DEFAULT NULL,
  `project_coemail` VARCHAR(45) NULL DEFAULT NULL,
  `project_active` TINYINT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`, `project_id`),
  INDEX `fk_project_org1_idx` (`org_id` ASC),
  CONSTRAINT `fk_project_org1`
    FOREIGN KEY (`org_id`)
    REFERENCES `formshare`.`org` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`userproj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`userproj` (
  `user_org` VARCHAR(32) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `project_org` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `access_type` TINYINT NULL COMMENT 'Admin,Editor,Member',
  PRIMARY KEY (`user_org`, `user_email`, `project_org`, `project_id`),
  INDEX `fk_userproj_project1_idx` (`project_org` ASC, `project_id` ASC),
  CONSTRAINT `fk_userproj_userorg1`
    FOREIGN KEY (`user_org` , `user_email`)
    REFERENCES `formshare`.`userorg` (`org_id` , `user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userproj_project1`
    FOREIGN KEY (`project_org` , `project_id`)
    REFERENCES `formshare`.`project` (`org_id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collaborator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collaborator` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  `collaborator_fname` VARCHAR(120) NULL DEFAULT NULL,
  `collaborator_lname` VARCHAR(120) NULL,
  `collaborator_password` VARCHAR(120) NULL DEFAULT NULL,
  `collaborator_active` TINYINT NULL DEFAULT NULL,
  `collaborator_cdate` DATETIME NULL DEFAULT NULL,
  `collaborator_email` TEXT NULL DEFAULT NULL,
  `collaborator_telephone` VARCHAR(120) NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  `sameas_org` VARCHAR(32) NULL,
  `sameas_project` VARCHAR(32) NULL,
  `sameas_collaborator` VARCHAR(32) NULL,
  PRIMARY KEY (`org_id`, `project_id`, `collaborator_id`),
  INDEX `fk_collaborator_project1_idx` (`org_id` ASC, `project_id` ASC),
  INDEX `fk_collaborator_collaborator1_idx` (`sameas_org` ASC, `sameas_project` ASC, `sameas_collaborator` ASC),
  CONSTRAINT `fk_collaborator_project1`
    FOREIGN KEY (`org_id` , `project_id`)
    REFERENCES `formshare`.`project` (`org_id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collaborator_collaborator1`
    FOREIGN KEY (`sameas_org` , `sameas_project` , `sameas_collaborator`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`form` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `form_name` VARCHAR(120) NULL DEFAULT NULL,
  `form_cdate` DATETIME NULL DEFAULT NULL,
  `form_directory` VARCHAR(120) NULL DEFAULT NULL,
  `form_schema` VARCHAR(13) NULL DEFAULT NULL,
  `form_accsub` INT(11) NULL DEFAULT NULL,
  `form_testing` INT(11) NULL DEFAULT '0',
  `form_incversion` INT(11) NULL DEFAULT '0',
  `form_stage` INT(11) NULL DEFAULT NULL,
  `form_pkey` VARCHAR(120) NULL DEFAULT NULL,
  `form_deflang` VARCHAR(120) NULL DEFAULT NULL,
  `form_yesno` VARCHAR(120) NULL DEFAULT NULL,
  `form_othlangs` TEXT NULL DEFAULT NULL,
  `form_sepfile` TEXT NULL DEFAULT NULL,
  `form_xlsfile` TEXT NULL DEFAULT NULL,
  `form_xmlfile` TEXT NULL DEFAULT NULL,
  `parent_org` VARCHAR(32) NULL,
  `parent_project` VARCHAR(32) NULL,
  `parent_form` VARCHAR(120) NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`),
  INDEX `fk_form_project1_idx` (`org_id` ASC, `project_id` ASC),
  INDEX `fk_form_form1_idx` (`parent_org` ASC, `parent_project` ASC, `parent_form` ASC),
  CONSTRAINT `fk_form_project1`
    FOREIGN KEY (`org_id` , `project_id`)
    REFERENCES `formshare`.`project` (`org_id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_form1`
    FOREIGN KEY (`parent_org` , `parent_project` , `parent_form`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`submission` (
  `submission_id` VARCHAR(64) NOT NULL,
  `submission_dtime` DATETIME NULL DEFAULT NULL,
  `submission_status` INT(11) NULL DEFAULT NULL,
  `md5sum` VARCHAR(120) NULL DEFAULT NULL,
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `collaborator_org` VARCHAR(32) NOT NULL,
  `collaborator_project` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  `sameas` VARCHAR(64) NULL,
  PRIMARY KEY (`submission_id`),
  INDEX `fk_submission_form1_idx` (`org_id` ASC, `project_id` ASC, `form_id` ASC),
  INDEX `fk_submission_collaborator1_idx` (`collaborator_org` ASC, `collaborator_project` ASC, `collaborator_id` ASC),
  INDEX `fk_submission_submission1_idx` (`sameas` ASC),
  CONSTRAINT `fk_submission_form1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submission_collaborator1`
    FOREIGN KEY (`collaborator_org` , `collaborator_project` , `collaborator_id`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submission_submission1`
    FOREIGN KEY (`sameas`)
    REFERENCES `formshare`.`submission` (`submission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collgroup` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `group_desc` TEXT NULL DEFAULT NULL,
  `group_cdate` DATETIME NULL DEFAULT NULL,
  `group_active` INT(11) NULL DEFAULT NULL,
  `extra` TEXT NULL DEFAULT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `group_id`),
  INDEX `fk_collgroup_project1_idx` (`org_id` ASC, `project_id` ASC),
  CONSTRAINT `fk_collgroup_project1`
    FOREIGN KEY (`org_id` , `project_id`)
    REFERENCES `formshare`.`project` (`org_id` , `project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collingroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collingroup` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  `group_org` VARCHAR(32) NOT NULL,
  `group_project` VARCHAR(32) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `access_type` TINYINT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `collaborator_id`, `group_org`, `group_project`, `group_id`),
  INDEX `fk_collingroup_collgroup1_idx` (`group_org` ASC, `group_project` ASC, `group_id` ASC),
  CONSTRAINT `fk_collingroup_collaborator1`
    FOREIGN KEY (`org_id` , `project_id` , `collaborator_id`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collingroup_collgroup1`
    FOREIGN KEY (`group_org` , `group_project` , `group_id`)
    REFERENCES `formshare`.`collgroup` (`org_id` , `project_id` , `group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`formaccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`formaccess` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  `form_org` VARCHAR(32) NOT NULL,
  `form_project` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `access_type` TINYINT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `collaborator_id`, `form_org`, `form_project`, `form_id`),
  INDEX `fk_formaccess_form1_idx` (`form_org` ASC, `form_project` ASC, `form_id` ASC),
  CONSTRAINT `fk_submitter_collaborator1`
    FOREIGN KEY (`org_id` , `project_id` , `collaborator_id`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formaccess_form1`
    FOREIGN KEY (`form_org` , `form_project` , `form_id`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`formgrpaccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`formgrpaccess` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `form_org` VARCHAR(32) NOT NULL,
  `form_project` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `access_cdate` DATETIME NULL,
  PRIMARY KEY (`org_id`, `project_id`, `group_id`, `form_org`, `form_project`, `form_id`),
  INDEX `fk_formgrpaccess_form1_idx` (`form_org` ASC, `form_project` ASC, `form_id` ASC),
  CONSTRAINT `fk_formgrpaccess_collgroup1`
    FOREIGN KEY (`org_id` , `project_id` , `group_id`)
    REFERENCES `formshare`.`collgroup` (`org_id` , `project_id` , `group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formgrpaccess_form1`
    FOREIGN KEY (`form_org` , `form_project` , `form_id`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`septable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`septable` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `table_desc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`, `table_name`),
  INDEX `fk_septable_form1_idx` (`org_id` ASC, `project_id` ASC, `form_id` ASC),
  CONSTRAINT `fk_septable_form1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`sepsection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`sepsection` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `section_id` VARCHAR(12) NOT NULL,
  `section_name` VARCHAR(120) NULL DEFAULT NULL,
  `section_desc` TEXT NULL DEFAULT NULL,
  `section_order` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`, `table_name`, `section_id`),
  CONSTRAINT `fk_sepsection_septable1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id` , `table_name`)
    REFERENCES `formshare`.`septable` (`org_id` , `project_id` , `form_id` , `table_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`sepitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`sepitems` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `table_name` VARCHAR(120) NOT NULL,
  `item_name` VARCHAR(120) NOT NULL,
  `item_desc` TEXT NULL DEFAULT NULL,
  `item_xmlcode` TEXT NULL DEFAULT NULL,
  `item_notdisplay` INT(11) NULL DEFAULT NULL,
  `item_order` INT(11) NULL DEFAULT NULL,
  `sepsection_org` VARCHAR(32) NOT NULL,
  `sepsection_project` VARCHAR(32) NOT NULL,
  `sepsection_form` VARCHAR(120) NOT NULL,
  `sepsection_table` VARCHAR(120) NOT NULL,
  `section_id` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`, `table_name`, `item_name`),
  INDEX `fk_sepitems_septable1_idx` (`org_id` ASC, `project_id` ASC, `form_id` ASC, `table_name` ASC),
  INDEX `fk_sepitems_sepsection1_idx` (`sepsection_org` ASC, `sepsection_project` ASC, `sepsection_form` ASC, `sepsection_table` ASC, `section_id` ASC),
  CONSTRAINT `fk_sepitems_septable1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id` , `table_name`)
    REFERENCES `formshare`.`septable` (`org_id` , `project_id` , `form_id` , `table_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sepitems_sepsection1`
    FOREIGN KEY (`sepsection_org` , `sepsection_project` , `sepsection_form` , `sepsection_table` , `section_id`)
    REFERENCES `formshare`.`sepsection` (`org_id` , `project_id` , `form_id` , `table_name` , `section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`jsonlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`jsonlog` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `log_id` VARCHAR(64) NOT NULL,
  `log_dtime` DATETIME NULL DEFAULT NULL,
  `json_file` TEXT NULL DEFAULT NULL,
  `log_file` TEXT NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `collaborator_org` VARCHAR(32) NOT NULL,
  `collaborator_project` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`, `log_id`),
  INDEX `fk_jsonlog_form1_idx` (`org_id` ASC, `project_id` ASC, `form_id` ASC),
  INDEX `fk_jsonlog_collaborator1_idx` (`collaborator_org` ASC, `collaborator_project` ASC, `collaborator_id` ASC),
  CONSTRAINT `fk_jsonlog_form1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id`)
    REFERENCES `formshare`.`form` (`org_id` , `project_id` , `form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jsonlog_collaborator1`
    FOREIGN KEY (`collaborator_org` , `collaborator_project` , `collaborator_id`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`jsonhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`jsonhistory` (
  `org_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  `form_id` VARCHAR(120) NOT NULL,
  `log_id` VARCHAR(64) NOT NULL,
  `log_sequence` VARCHAR(12) NOT NULL,
  `log_dtime` DATETIME NULL DEFAULT NULL,
  `log_action` INT(11) NULL DEFAULT NULL,
  `log_commit` VARCHAR(12) NULL DEFAULT NULL,
  `log_notes` TEXT NULL DEFAULT NULL,
  `collaborator_org` VARCHAR(32) NOT NULL,
  `collaborator_project` VARCHAR(32) NOT NULL,
  `collaborator_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`org_id`, `project_id`, `form_id`, `log_id`, `log_sequence`),
  INDEX `fk_jsonhistory_jsonlog1_idx` (`org_id` ASC, `project_id` ASC, `form_id` ASC, `log_id` ASC),
  INDEX `fk_jsonhistory_collaborator1_idx` (`collaborator_org` ASC, `collaborator_project` ASC, `collaborator_id` ASC),
  CONSTRAINT `fk_jsonhistory_jsonlog1`
    FOREIGN KEY (`org_id` , `project_id` , `form_id` , `log_id`)
    REFERENCES `formshare`.`jsonlog` (`org_id` , `project_id` , `form_id` , `log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jsonhistory_collaborator1`
    FOREIGN KEY (`collaborator_org` , `collaborator_project` , `collaborator_id`)
    REFERENCES `formshare`.`collaborator` (`org_id` , `project_id` , `collaborator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`userlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`userlog` (
  `log_entry` VARCHAR(64) NOT NULL,
  `log_datetime` DATETIME NULL DEFAULT NULL,
  `access_type` INT(11) NULL DEFAULT NULL,
  `table` VARCHAR(45) NULL,
  `action` TINYINT NULL,
  `user` VARCHAR(255) NULL,
  `org` VARCHAR(32) NULL DEFAULT NULL,
  `project` VARCHAR(32) NULL,
  `form` VARCHAR(120) NULL,
  `collaborator` VARCHAR(32) NULL,
  `group` VARCHAR(12) NULL,
  `septable` VARCHAR(120) NULL,
  `sepsection` VARCHAR(12) NULL,
  `sepitem` VARCHAR(120) NULL,
  PRIMARY KEY (`log_entry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `formshare`.`collaboratorlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formshare`.`collaboratorlog` (
  `log_entry` VARCHAR(64) NOT NULL,
  `log_datetime` DATETIME NULL DEFAULT NULL,
  `access_type` INT(11) NULL DEFAULT NULL,
  `interface` TINYINT NULL,
  `action` INT(3) NULL,
  `user` VARCHAR(255) NULL,
  `org` VARCHAR(32) NULL DEFAULT NULL,
  `project` VARCHAR(32) NULL,
  `form` VARCHAR(120) NULL,
  `collaborator` VARCHAR(32) NULL,
  `log` VARCHAR(64) NULL,
  `commit` VARCHAR(12) NULL,
  `schema` VARCHAR(13) NULL,
  `table` VARCHAR(120) NULL,
  PRIMARY KEY (`log_entry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
