from celery import Celery
import configparser
from pkg_resources import iter_entry_points
from formshare.config import celery_config

FORMSHARE_INI_FILE = '{{FORMSHARE_INI_FILE}}'
TASKS_ENTRY_POINT_GROUP = 'formshare.tasks'
PLUGINS_ENTRY_POINT_GROUP = 'formshare.plugins'


def just_a_warning():
    """
    This file has been generated by configure_celery
        You should not need to edit this file, however if you
        are moving the installation of Formshare to another directory
        then you either need to call again configure_celery or
        edit the FORMSHARE_INI_FILE so it points to the new path
    """


def get_ini_value(key, default=None):
    try:
        config = configparser.ConfigParser()
        config.read(FORMSHARE_INI_FILE)
        return config.get('app:main', key)
    except:
        return default


def get_tasks():
    tasks = []
    plugins = get_ini_value(PLUGINS_ENTRY_POINT_GROUP, '').split()
    for plugin in plugins:
        if isinstance(plugin, str):
            iterator = iter_entry_points(
                group=TASKS_ENTRY_POINT_GROUP,
                name=plugin
            )
            entry_point = next(iterator, None)
            if entry_point:
                tasks.append(entry_point.module_name)
    return tasks


celeryApp = Celery(get_ini_value('celery.taskname'), broker=get_ini_value('celery.broker'),
                   backend=get_ini_value('celery.backend'), include=get_tasks())
celeryApp.config_from_object(celery_config)
